### ISSUE TITLE
export is not working on Firefox/MacOS

### ISSUE THREAD

**Issue by arademaker** [jonorthwash/ud-annotatrix#101]

**Comment by jonorthwash** [comment]
This feature was implemented this last winter (northern hemisphere) but not tested since then, so it's no surprise it's stopped working with all the other changes.

**Comment by ftyers** [comment]
@arademaker I've made a small change and now it works in my Firefox, could you check the latest version?

**Comment by arademaker** [comment]
working now.

**Comment by jonorthwash** [comment]
Which revision fixed this?
