### ISSUE TITLE
should export button say import?

### ISSUE THREAD

**Issue by flammie** [jonorthwash/ud-annotatrix#102]
The button for uploading local file has the label export, from a traditional desktop editor application point-of-view opening a file is more like an import.

**Comment by jonorthwash** [comment]
There's supposed to be both actually.  It sounds like they got merged at some point...

**Comment by flammie** [comment]
Well, like I said in the other bug, it is confusing me too, so it needs at least some redesigning I guess.

**Comment by ftyers** [comment]
For me thre are two buttons, one says 

"Load Corpora from file:  Choose File  "

The other says: "Export Corpus"

The first one puts the treebank in the interface the second one downloads a copy of the treebank, Agreed it's not completely clear, but there do seem to be two buttons, and the functionality works (mostly).

**Comment by flammie** [comment]
yeah so basically it's an UI issue. The <input type="file"/> button or other widget is defined by the browser. Mine says [Dateien auswählen] Keine ausgewählt. The labe on the button in all my browsers suggest selecting, but here it actually does uploading, this is unexpected. Traditional upload forms have a submit button for this operation, like so: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#Using_file_inputs. This is why I thought the export button is import button. Maybe this automatic upload is just modern web design, it can also be left like that.

**Comment by ftyers** [comment]
How about this: Change "Load corpora from file" to "Select a file to upload" ?

**Comment by jonorthwash** [comment]
Was this fixed?  Which revision?
