### ISSUE TITLE
Download annotations

### ISSUE THREAD

**Issue by flammie** [jonorthwash/ud-annotatrix#103]
Is there a way to download the annotated data?

**Comment by rueter** [comment]
On OS 10.10 (I can't update my machine to anything newer) I am unable to download materials on Firefox/Chrome/Safari. I hope there will soon be a solution.
rueter

**Comment by ftyers** [comment]
Download (i.e. "Export Corpus" button) works for me in Debian/Chromium:
```
Version 61.0.3163.100 (Developer Build) built on Debian 9.1, running on Debian buster/sid (64-bit)
```
What versions do you guys have?

**Comment by ftyers** [comment]
The code that does the downloading is:
```
//Export Corpora to file
function exportCorpora() {
    var finalcontent = getTreebank();

    var link = document.createElement('a');
    var mimeType = 'text/conllu';

    link.setAttribute('download', FILENAME);
    link.setAttribute('href', 'data:' + mimeType + ';charset=utf-8,' + encodeURIComponent(finalcontent));
    link.click();
}
```
This says that is it not supported in some browsers: http://caniuse.com/#feat=download 

Perhaps the code can be replaced with something more functioning in all browsers.

**Comment by ftyers** [comment]
The missing piece was:
```
    document.body.appendChild(link);
```

**Comment by ftyers** [comment]
Hopefully fixed.

**Comment by jonorthwash** [comment]
Which revision did you commit in which this was hopefully fixed?
