### ISSUE TITLE
Inform user of strict cookie settings

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#105]
When "block third-party cookies" is enabled in Chromium, this error happens:
```
Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```
The solution is to unblock third-party cookies. It would be good to be able to tell the user this.

**Comment by ftyers** [comment]
Fixed, now it warns the user so they know what to do, maybe in the future we want to be able to fix this without allowing third-party cookies.

**Comment by jonorthwash** [comment]
Which revision fixes this?
