### ISSUE TITLE
problems with commented text and rough conllu in import-export firefox and chrome

### ISSUE THREAD

**Issue by rueter** [jonorthwash/ud-annotatrix#109]
Hi

Hi, I am trying to use Firefox 52.4.1 (64-bit) and Chrome 61.0.3163.100 (Official Build) (64-bit) on OSX 10.10.5.
Firefox has a browse button that I can choose my file with.

    I discard the previous corpus with the button
    browse and select a file with 3 commented lines followed by a conllu-formated sentence AND a blank line:

```
#sent_id = chapID01:paragID1:sentID1 
# text = Кечаень сыргозтизь налкставтыця карвот . 
# text[eng] = Kechai was awoken by annoying flies. 
1 Кечаень Кечай N N Sem/Ant_Mal|Prop|SP|Gen|Indef 2 obj _ Кечаень 
2 сыргозтизь сыргозтемс V V TV|Ind|Prt1|ScPl3|OcSg3 0 root _ сыргозтизь 
3 налкставтыця налкставтомс PRC Prc V|TV|PrcPrsL|Sg|Nom|Indef 4 amod налкставтыця 
4 карвот карво N N Sem/Ani|N|Pl|Nom|Indef 2 nsubj _ карвот 
5 . . CLB CLB CLB 2 punct _ .
```
The data uploaded is not consistent:

Only one of the commented lines from the third sentence appears as the first sentence.
the second sentence is from line 912 of my document it too is commented

The first time I get what looks like text without conllu formating is
```
#sent_id = chapID05:paragID8:sentID1
text = — Виде . . . Пекшенень . . . — моткодезевсь бодясь , — инжеть састь . . .
text[eng] = That's right... the Pekshes..., the old man muttered, are having guests.
where the machine grabs: Пекшенень as its own input line. 
```

**Comment by ftyers** [comment]
I tried the file you sent me. There was a lot of uncommented XML, the best thing to do is to try and clean up the file and load it again. You might try to click "discard corpus" before uploading, and then after uploading refresh the page.

**Comment by jonorthwash** [comment]
Apparently due to malformed data.  If there's a bug triggered by something that shouldn't be triggering a bug, feel free to reopen.
