### ISSUE TITLE
no way to input one-sentence-per-line raw text

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#117]
Currently a single sentence can be dummy tokenised and converted to conllu.  It would also be good to accept raw text input that has one sentence per line.

See #79, where a switch was presumably added to catch this use case.

**Comment by ftyers** [comment]
This works if it's from a file or if all the sentences are on the same line.

**Comment by jonorthwash** [comment]
And will probably think it's sdparse if there are parentheses in the sentence.  So sdparse format detection also needs to be strengthened.

**Comment by ftyers** [comment]
Yep, although these are really secondary features. SDParse and plain text input are only really used for demonstration purposes, for most real annotation people will use CG or CoNLL-U input (I'm guessing). Better format detection is always welcome, but I don't think it should be a priority.

**Comment by jonorthwash** [comment]
I think parsing plain text is a good way to bootstrap a corpus.  Yes, it's reasonably trivial to turn plain text into raw CG and CoNLLU, but most of this stuff is trivial—the idea is that we're saving people time, especially people who just want to annotate and don't want to learn a whole bunch of regex syntax and stuff.

**Comment by jonorthwash** [comment]
Semi duplicated in #123, which should probably focus on parentheses, while this issue should remain about the multi-line thing.

**Comment by ftyers** [comment]
Fixed in 4c8fa2a.
