### ISSUE TITLE
Deprels should default for some POS

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#118]
Typing out those deprels can be pretty tedious. Let's save the user some time by adding some by default, e.g.

* If the dependent is PUNCT set the deprel to `punct`
* If the dependent is DET set the deprel to `det`

Note that these should only apply to arcs without labels. If the user changes it then it shouldn't change it back.

**Comment by ftyers** [comment]
Another possibility would be for the interface to "learn" stuff from what the user annotates. I'm pretty sure Toolbox does something like that.

**Comment by ftyers** [comment]
Preliminary support in 35324bb.

**Comment by jonorthwash** [comment]
Made a bit saner in https://github.com/jonorthwash/ud-annotatrix/commit/8043de206305579f1fff3bc69597f98028456a12, though it probably needs to be tested.

**Comment by ftyers** [comment]
I think we can say that "preliminary support" is ok here, could be improved though, but I leave that to future issues.
