### ISSUE TITLE
Impossible to type spaces into the conllu box

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#129]
When you type a space, the cursor moves to the end of the text . So if you have for example:
```
# sent_id = _
# text = This is a test .
1	This	_	_	_	_	_	_	_	_
2	is	_	_	_	_	_	_	_	_
3	a	_	_	_	_	_	_	_	_
4	test	_	_	_	_	_	_	_	_
5	.	_	_	_	_	_	_	_	_
```
And you want to type `# labels = foo bar` as soon as you do the first space the cursor moves to the end.

**Comment by jonorthwash** [comment]
Seems to be fixed in https://github.com/jonorthwash/ud-annotatrix/commit/da5d6e31626fd1da410fdbd488b1c58e5f3ea541.

**Comment by keggsmurph21** [comment]
old, closing
