### ISSUE TITLE
Autocomplete does not work

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#130]
For some reason autocomplete stopped working between 9c859ffc128b0167d1d982b452505164a58dcb68 and 4c8fa2ae3496ba15f8a4905cb0d6e3804a2c4f73

**Comment by jonorthwash** [comment]
Seems to be fixed in https://github.com/jonorthwash/ud-annotatrix/commit/da5d6e31626fd1da410fdbd488b1c58e5f3ea541.  Feel free to reopen the issue if it continues to be a problem.
