### ISSUE TITLE
Can't select/delete nodes that are errors

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#131]
It's probably got to do with the selectors, e.g. all the code that works with

```
  "selector": "edge.dependency",
```

Has to work with 
```
  "selector": "edge.dependency-error",
```
too

Or we should work out a better way of changing the colour of the arcs when they are errors.

**Comment by jonorthwash** [comment]
https://github.com/jonorthwash/ud-annotatrix/commit/79c4c47067670e518761fe90341ecd849b56ef12 implements a hack for this.  But you still can't delete it until you add text...

**Comment by jonorthwash** [comment]
https://github.com/jonorthwash/ud-annotatrix/commit/923ad7318a289d61c15b8eb9a604ef8d632963a0 seems to fix it
