### ISSUE TITLE
Impossible to paste more than one sentence <s>while in the CoNLL-U mode.</s>

### ISSUE THREAD

**Issue by ifsdotname** [jonorthwash/ud-annotatrix#136]
Related to #129 

For example, when I (at once) try to paste these two sentences (taken from http://universaldependencies.org/format.html):

```
# sent_id = 1
# text = They buy and sell books. 
1   They     they    PRON    PRP    Case=Nom|Number=Plur               2   nsubj   2:nsubj|4:nsubj   _
2   buy      buy     VERB    VBP    Number=Plur|Person=3|Tense=Pres    0   root    0:root            _
3   and      and     CONJ    CC     _                                  4   cc      4:cc              _
4   sell     sell    VERB    VBP    Number=Plur|Person=3|Tense=Pres    2   conj    0:root|2:conj     _
5   books    book    NOUN    NNS    Number=Plur                        2   obj     2:obj|4:obj       SpaceAfter=No
6   .        .       PUNCT   .      _                                  2   punct   2:punct           _

# sent_id = 2
# text = I have no clue.
1   I       I       PRON    PRP   Case=Nom|Number=Sing|Person=1     2   nsubj   _   _
2   have    have    VERB    VBP   Number=Sing|Person=1|Tense=Pres   0   root    _   _
3   no      no      DET     DT    PronType=Neg                      4   det     _   _
4   clue    clue    NOUN    NN    Number=Sing                       2   obj     _   SpaceAfter=No
5   .       .       PUNCT   .     _                                 2   punct   _   _

```

the empty line between them disappears and no tree shows up:
![bildschirmfoto vom 2017-10-25 22-15-36](https://user-images.githubusercontent.com/23083718/32018788-ac787332-b9d3-11e7-8e05-3ddad2d3606a.png)

It seems that it doesn't matter in which mode (plain text or CoNLL-U) annotatrix is in before I paste the sentences into it -- initially, when I load the page, it is in, and whenever I empty the box, it reverts to the 'plain text' mode, but if I paste the above two sentences, it switches to the 'CoNLL-U' mode with the above issue.

**Comment by ftyers** [comment]
I think I've managed to fix this in 758b5fa can you check ?

**Comment by ifsdotname** [comment]
Indeed it works now. Update the instance on your page ;)

**Comment by ftyers** [comment]
Will do!
