### ISSUE TITLE
Deletion doesn't work

### ISSUE THREAD

**Issue by KatyaAplonova** [jonorthwash/ud-annotatrix#137]
It isn't possible to delete arcs anymore...

**Comment by jonorthwash** [comment]
Broken by https://github.com/jonorthwash/ud-annotatrix/commit/923ad7318a289d61c15b8eb9a604ef8d632963a0.  Working on a fix now.

**Comment by jonorthwash** [comment]
Should be fixed by https://github.com/jonorthwash/ud-annotatrix/commit/b3856f.  Please reopen if you continue to notice problems with deletion of arcs.
