### ISSUE TITLE
all words converted to PUNCT

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#138]
When I try to import sentences into annotatrix, all are tagged as `PUNCT`.
![2017-10-29-11 45 05_001](https://user-images.githubusercontent.com/963849/32145412-a735ac64-bc9e-11e7-85b4-37082c4602cf.png)

**Comment by ftyers** [comment]
`converters.js`:

```
       if(sent.tokens[i]['form'].match(/\W/)) {
         sent.tokens[i]['upostag'] = 'PUNCT';
       }
```

Probably the regex needs to be rewritten.

**Comment by jonorthwash** [comment]
Appears to be fixed by https://github.com/jonorthwash/ud-annotatrix/commit/4ac510.
