### ISSUE TITLE
all following lines deleted when newline inserted

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#140]
If you insert a new line in CoNLL-U format by pressing enter, all lines below it are deleted.

**Comment by ftyers** [comment]
Can you give a clearer example ?

**Comment by jonorthwash** [comment]
I enter a sample sentence in plain text, open in CoNLL-U view:
![2017-10-29-12 55 38_001](https://user-images.githubusercontent.com/963849/32146069-8dd4fdf6-bca8-11e7-9bc9-c3acaefaf1ce.png)
Then I go to the end of token 3's line, and press enter:
![2017-10-29-12 55 51_001](https://user-images.githubusercontent.com/963849/32146070-90534678-bca8-11e7-92d2-727defed654b.png)
Token lines 4 to 6 are "lost", and appear as a second sentence:
![2017-10-29-12 57 03_001](https://user-images.githubusercontent.com/963849/32146085-bae946a8-bca8-11e7-801e-d123777670b7.png)

**Comment by ftyers** [comment]
That's probably the expected functionality, why would you want to put a space between two blocks otherwise ?

**Comment by jonorthwash** [comment]
> why would you want to put a space between two blocks otherwise ?
If you want to add a token or subtoken?

**Comment by ftyers** [comment]
Wouldn't the way to do that be to split a token and then edit it ? Although I'm not sure what the use case is for adding/removing tokens in the text. It's an editor for dependency trees more than a text editor, I think we should optimise for that and expect that the users check the sentences before adding them. (e.g. I don't think we should support formatting either)

**Comment by jonorthwash** [comment]
> Wouldn't the way to do that be to split a token and then edit it ?

In the graph, yes, but how would you do it in the textbox?

I think the final answer is that we CoNLLU lined up like a table, with a mode to copy the rawtext, but only edit as a table.

**Comment by jonorthwash** [comment]
If this isn't a bug, then #129 probably isn't either.

**Comment by jonorthwash** [comment]
Aha, seems to be related to #136.  Perhaps the correct behaviour is to split it to a new sentence when it's clearly the _beginning_ of a new tree?

**Comment by ftyers** [comment]
This is _really_ problematic when you've loaded a large corpus and try to add a new line for the comment. It discards all the previous work. We should not be deleting _anything_ that follows.

**Comment by jonorthwash** [comment]
>  It discards all the previous work

Does it?  Or does it just move it onto the next "page"?

**Comment by jonorthwash** [comment]
I believe it was https://github.com/jonorthwash/ud-annotatrix/commit/758b5fadb7eeed84fca1dcfd59fe550c1bb0bf88 that created this behaviour.  Could someone test and verify?

**Comment by maryszmary** [comment]
> I believe it was 758b5fa that created this behaviour. Could someone test and verify?

Yes, that's true. I'm fixing this.
