### ISSUE TITLE
conversion from plain text to CoNLL-U only happens once

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#144]
If a plain-text sentence has already been converted to CoNLL-U (or simply loaded in CoNLL-U format?), then a new sentence entered as plain text cannot be converted.  The CoNLL-U and CG tabs/buttons fail to do anything useful when clicked.  The following appears in the console when CoNLL-U is clicked:
```
converters.js:44 Uncaught TypeError: Cannot read property 'match' of undefined
    at plainSent2Conllu (converters.js:44)
    at String.<anonymous> (converters.js:82)
    at Function.each (jquery-3.2.1.min.js:2)
    at plainText2Conllu (converters.js:81)
    at toConllu (converters.js:6)
    at viewAsConllu (gui.js:729)
    at HTMLAnchorElement.onclick (VM103 annotator.html:159)
plainSent2Conllu @ converters.js:44
(anonymous) @ converters.js:82
each @ jquery-3.2.1.min.js:2
plainText2Conllu @ converters.js:81
toConllu @ converters.js:6
viewAsConllu @ gui.js:729
onclick @ VM103 annotator.html:159
```

**Comment by jonorthwash** [comment]
Note: it works after the corpus is cleared (the "discard" / trash can button).

**Comment by jonorthwash** [comment]
This also seems to be the case when a corpus is loaded in CoNLL-U format.  So it seems to be *corpus*-level conversion, not sentence-level.

@rueter is reporting something similar.

**Comment by keggsmurph21** [comment]
this is fixed
