### ISSUE TITLE
dosen't work with https

### ISSUE THREAD

**Issue by flammie** [jonorthwash/ud-annotatrix#15]
Im not sure if this should be ud-annotatrix or github.io issue, but the page: https://jonorthwash.github.io/visualise.html doesn't work. When using https everywhere extension, it is impossible to open the http version of the page. Usually this kind of bugs can be fixed by changing all links to point // instead of http://. The error messages:

`Mixed Content: The page at 'https://jonorthwash.github.io/visualise.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,400italic,600italic,700italic&subset=latin&effect=smoothing'. This request has been blocked; the content must be served over HTTPS.
head.load.min.js:8 Mixed Content: The page at 'https://jonorthwash.github.io/visualise.html' was loaded over HTTPS, but requested an insecure script 'http://spyysalo.github.io/annodoc/lib/local/annodoc.js'. This request has been blocked; the content must be served over HTTPS.
y @ head.load.min.js:8
head.load.min.js:8 Mixed Content: The page at 'https://jonorthwash.github.io/visualise.html' was loaded over HTTPS, but requested an insecure script 'http://spyysalo.github.io/conllu.js/conllu.js'. This request has been blocked; the content must be served over HTTPS.
y @ head.load.min.js:8
https://jonorthwash.github.io/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.min.js:2 Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://jonorthwash.github.io" from accessing a cross-origin frame.
    at contents (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2:5154)
    at Function.map (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:14862)
    at ot.fn.init.ot.fn.(anonymous function) [as contents] (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:2:5271)
    at HTMLIFrameElement.eval (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/views/overlay/ActivityMonitorOverlayView.js:1:1894)
    at Function.each (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:14059)
    at ot.fn.init.each (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/vendor/jquery.min.js:1:11922)
    at e.bindActivityDetectors (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/views/overlay/ActivityMonitorOverlayView.js:1:1853)
    at e.init (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/components/ActivityMonitor/ActivityMonitorController.js:1:255)
    at onLoaded (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/content.js:1:979)
    at eval (chrome-extension://laankejkbhbdhmipfmgcngdelahlfoji/core/ComponentFactory.js:1:943)
visualise.html:1 Mixed Content: The page at 'https://jonorthwash.github.io/visualise.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,400italic,600italic,700italic&subset=latin&effect=smoothing'. This request has been blocked; the content must be served over HTTPS.`

**Comment by SilentFlame** [comment]
@flammie as per what I know we can load `https://` requests on 'https://' but not vice versa, which is the case for the above error.
Basically if `https://` sites load `http://` requests then site will be prone to MITM attacks, which is the reason it doesn't.

So either we replace all the inside URL's having `http://` with `https://` to load it on the [https://jonorthwash.github.io/visualise.html](https:// request page), or else use the `http://` everywhere(current case).

If needed I can make a PR making all the `http://` -> `https://`.

**Comment by jonorthwash** [comment]
Doesn't the correct solution involve `//` instead?

**Comment by flammie** [comment]
> Doesn't the correct solution involve `//` instead?

Yes, that should do it.

**Comment by SilentFlame** [comment]
Ohh, will test it once and try to make a PR for the same.

**Comment by maryszmary** [comment]
Fixed by @MidasDoas by making two external links protocol-agnostic, then I fixed it to work locally.
Now the solution looks as follows:

var protocol = (document.location.protocol !== 'file:') ? document.location.protocol : 'http:';
...
protocol + '//spyysalo.github.io/annodoc/lib/local/annodoc.js',
protocol + '//spyysalo.github.io/conllu.js/conllu.js',

In the current state, the interface works with HTTP, HTTPS (https://maryszmary.github.io/ud-annotatrix/visualise.html) and locally.

**Comment by jonorthwash** [comment]
@maryszmary , could you mention the revision that solved the issue when you close them?

**Comment by maryszmary** [comment]
HTTPS problem fixed in 5d3340c633a22e8180273960aebe9195205a1dca.
Issue with working locally after it fixed in e01053799f2356036ed699af0506ee7c99edf11a.
