### ISSUE TITLE
Does table view make sense in CG mode?

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#154]
When you click on table view, and then switch to CG, it should switch to code view (probably?)

**Comment by jonorthwash** [comment]
Or perhaps we want a different table view for CG? :D

**Comment by ftyers** [comment]
I don't think it would make much sense, CG is much easier to read than CoNLL-U by default, also we don't need all the validation steps that we have with CoNLL-U and in any case we can switch between them.

**Comment by jonorthwash** [comment]
That certainly would work as the behaviour for the time being, and we can decide later if an optional enhanced view for CG makes any sense.
