### ISSUE TITLE
Crossing arcs in graph display

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#158]
1c0c79c introduced a problem of crossing arcs:

![captura de 2017-11-03 09-32-58](https://user-images.githubusercontent.com/449545/32365416-11539c58-c07a-11e7-9587-bc5cf31f35f8.png)

**Comment by jonorthwash** [comment]
Unlikely that it was that commit..

**Comment by jonorthwash** [comment]
This is still an issue for overlapping dependencies.  Someone seemed to've added a hack to "fix" this that made all right-pointing arcs about 20% higher than left-pointing arcs of the same level.  I removed this hack as soon as I noticed it.
