### ISSUE TITLE
no way to scroll up/down over graph because it zooms

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#159]
I propose the following behaviour:

* scrolling scrolls the page
* shift+scrolling zooms the graph.

**Comment by ftyers** [comment]
Fixed, don't remember the commit.

**Comment by jonorthwash** [comment]
Shift+scrolling seems to horizontal scroll for me.

**Comment by ftyers** [comment]
I really don't like the idea of scrolling over the graph causing scrolling. On my small screen, most of the time I'm scrolling on the page it's because i'm going from graph to code and back. It's annoying to have to move my mouse out of the graph in order to do that. Maybe shift + scrolling could scroll on the graph ?

**Comment by jonorthwash** [comment]
> It's annoying to have to move my mouse out of the graph in order to do that.

Exactly.

> I really don't like the idea of scrolling over the graph causing scrolling.

I don't get it.  You seem to be arguing with yourself?

**Comment by jonorthwash** [comment]
Okay, I mostly agree with you (for the moment), but the shift+zoom behaviour doesn't seem to work as described. I'm reopening the issue for that reason.

I wonder if it's because of the issue with the being just a little wider than the window, as described elsewhere?

**Comment by ftyers** [comment]
Fixed in 00f2f8b. See function `onScroll` in `visualiser.js`.
