### ISSUE TITLE
should remember table view on page reload

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#166]
When the page is reloaded, in addition to remembering the corpus, annotatrix should remember if table view was active or not.

**Comment by jonorthwash** [comment]
And more generally probably also:
- which view was selected (CoNLLU vs. CG3), as well as
- which sentence/tree was active

**Comment by jonorthwash** [comment]
There might be some minor bugs with the view tabs that overlap with this issue.  I don't see open issues for them, so just beware, I guess.

**Comment by keggsmurph21** [comment]
this is all fixed, this data (gui settings) gets saved to `localStorage`/`server` along with the rest of the sentence data
