### ISSUE TITLE
Add support for using a backend

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#17]
Like with `apertium-apy` and `apertium-html-tools` it would be good to have support for using a server to store the treebanks, to allow for collaborative editing. This is a meta-issue and should probably be broken into various sub-issues.

**Comment by maryszmary** [comment]
So, this implies that users should be able to create their own accounts, save their treebanks and share with other users?

**Comment by ftyers** [comment]
I think we can leave all stuff about authorisation/account creation out of the first version. Think more like Etherpad/Piratepad, where you can go to a URL, write your name and edit. But with the treebanks stored on a remote server.

**Comment by jonorthwash** [comment]
I think the treebanks should be stored locally, in cookies, and optionally shared with other users connected to the server.  I'm thinking more like IRC channels than like the anonymous model of etherpad.

However this ends up being done, it's likely to be a big undertaking.

**Comment by ftyers** [comment]
Is it possible to store nearly 100s of M in cookies ? The treebanks we work with are mostly small, but there are much bigger treebanks.

```
11M -rw-r--r-- 1 fran fran 11M mar 19 15:52 UD_Russian-SynTagRus/ru_syntagrus-ud-dev.conllu
79M -rw-r--r-- 1 fran fran 79M mar 19 15:52 UD_Russian-SynTagRus/ru_syntagrus-ud-train.conllu
```

I think it's good to be flexible with the backend storage if possible.

**Comment by jonorthwash** [comment]
Hmm, I'm worried about the idea of "uploading" files of those sizes even to a local interface.  Keeping that much stuff in memory even might not be ideal.

**Comment by ftyers** [comment]
The person to ask about this is probably Filip, Dan, or Olya or someone else with experience of large annotation projects. I can also make enquiries at EACL next week.

**Comment by ftyers** [comment]
@fginter can you comment a bit on the Flask stuff we were talking about ?

**Comment by jonorthwash** [comment]
Okay, my understanding of the backend is something like this:

A [python] script included in the repo that when run serves the current interface, but enables backend support in it—and also provides the backend support.

The basic backend support is:
* saving and loading a project (i.e., a corpus / series of sentences)

More advanced backend features (probably for [phase 3](https://github.com/jonorthwash/ud-annotatrix/milestone/3)) include:
* selecting/managing available projects
* [more advanced?] [undo/redo history](#39)
* [more advanced?] [commit feature](#4), perhaps integrated with undo/redo history?
* setting the backend to talk to a server that isn't serving it

**Comment by maryszmary** [comment]
Basic functionality added in 785a4c4cc765f1d3548304a3f6cf7f31b1cf55d7.

**Comment by jonorthwash** [comment]
The advanced features should be broken out into new issues.

**Comment by maryszmary** [comment]
Yes, sure. I will also add issues breaking reimplementing the gui into parts (e.g. make a SDparse to conllu converter) later. Some of the issues in this repo actually consist of a lot of different tasks...
