### ISSUE TITLE
progress indicator of how much of the current file has been fully annotated

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#172]
it would be cool to have a line indicating the current progress perhaps with a percentage in very small type at the very top of the page. Or perhaps under the text box.

**Comment by jonorthwash** [comment]
What algorithm would it use to determine whether a sentence has been annotated or not?  Just check to see if every word has a head and relation label?  Or do we want to base it on POS and/or morphological features too?

**Comment by ftyers** [comment]
just form + head + relation + UPOS, that's the UD minimum. :)
