### ISSUE TITLE
no way to delete a supertoken ? 

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#173]
Once you split two tokens and merge them into a single supertoken, it doesn't seem to be possible to get rid of the supertoken (e.g. undo the merge). I would propose clicking on the supertoken and then pressing 'del/backspace'.

**Comment by ftyers** [comment]
Seems there is code for this, it just doesn't work:
```
gui.js:313 Uncaught TypeError: Cannot read property 'tokens' of undefined
    at removeSup (gui.js:313)
    at keyUpClassifier (gui.js:259)
    at HTMLDocument.<anonymous> (annotator.js:57)
    at HTMLDocument.dispatch (jquery-3.2.1.min.js:3)
    at HTMLDocument.q.handle (jquery-3.2.1.min.js:3)
```

**Comment by maryszmary** [comment]
By the time I saw the issue, the problem with deleting supertokens was that the lines representing the subtokens were switching in conllu. Fixed that.

**Comment by maryszmary** [comment]
However, I see one more problem now, which is: when you have 2+ supertokens, and then remove some supertoken at the beginning, you can no more remove the ones which come after it because of the indices shift.

**Comment by maryszmary** [comment]
No, the problem was actually worse: there's a logical error in how removeSup was implemented. Working on it.
