### ISSUE TITLE
jump to new sentence when added

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#174]
Currently if you're on sentence 1/349853145 and you click "add", it adds a sentence at the end and you stay where you are.

It should instead do one of two possible things:
- After adding sentence 349853146, it should bring you to it, **or**
- It should add a sentence immediately after the current one (in this example, sentence 2), and bring you to it.

Either way you shouldn't stay on the sentence you were looking at before you added.

**Comment by ftyers** [comment]
I really think we shouldn't be encouraging people to use those buttons when thinking about large files. The point is that when you are editting a large file, probably it came from somewhere and has IDs and stuff and order of sentences. You probably don't want to be adding sentences to large files. When adding sentences to a file you're making in annotatrix, then it makes sense, but in that case I think the current behaviour is ok, or it should switch to the one you just added. 

In any case the distinction between "corpus" and "sentences" and "converted"/"viewed as" is a bit undefined at the moment, and needs to be made more concrete. It would help to think of typical use cases and then define the behaviour based on that. Annotatrix should not become a "tool for everything" (e.g. reimplementing emacs), but a tool with well defined characteristics and sensible defaults.

**Comment by jonorthwash** [comment]
Perhaps part of this is thinking about having options to fill in IDs automatically.

For example, in one scenario, I might want to be slowly building a corpus that I haven't released yet.  Mostly I'm adding sentence I'm getting from source A, but maybe I have some from source B, or switch entirely to getting the sentences from source B.

Then what if I want to go work on another treebank for a while.  I should be able to export (or better: save to server) the one I was working on, and switch to the new one.

> the distinction between "corpus" and "sentences" and "converted"/"viewed as"

In general, I don't think there should be a different set of behaviours based on where the corpus came from, or what format it was in originally.  Annotatrix should deal with CoNLL-U natively, and everything else is a conversion to (on "import") or from (for "viewed as") that.  This whole thing probably needs its own issue.

**Comment by keggsmurph21** [comment]
current behavior of clicking the "+" button is to add a sentence directly after the current sentence

i haven't done any thinking about automatically filling in IDs, but that should probably be a separate issue if it's still something you guys are thinking about
