### ISSUE TITLE
Not-massive treebanks do not load

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#181]
Even loading smaller treebanks (with approx 5,000 trees) like the Swedish treebank training data (see #178). We should support loading treebanks up to the maximum size of `localStorage` and give the user feedback when that limit is overrun or likely to be overrun.

**Comment by ftyers** [comment]
I've added in 526258c code which shows the user approx. how much available space they have in `localStorage` when they click on the file upload modal. But we should make this nicer, and we should also advise the user if they overrun the limit and point them at instructions on how to set up and use the server code. "Silently fail" is a bit PHP for my liking... :D

**Comment by ftyers** [comment]
@maryszmary can we close this now ?

**Comment by maryszmary** [comment]
I think, yes.
There are still problems with it in standalone version. Moreover, I think, there could be a way to solve them or at least optimize the memory. However, the server version allows to load big corpora, and the problem of solving this problem for stand-alone could be another issue.

**Comment by ftyers** [comment]
Closing this as it was fixed quite a while ago.
