### ISSUE TITLE
refactor gui.js

### ISSUE THREAD

**Issue by maryszmary** [jonorthwash/ud-annotatrix#182]
- [ ] make the code more readable and consistent:
  - [ ] split up long functions into smaller ones
  - [ ] make variable names self-expanatory
- [ ] get rid of unnecessary global variables
- [ ] write a doc-string for every function

**Comment by ftyers** [comment]
The code 

```
var POS2RELmappings = {
        "PUNCT": "punct",
        "DET": "det",
        "CCONJ": "cc",
        "SCONJ": "mark"
}
```

and

```
    // If the target POS tag is PUNCT set the deprel to @punct [99%]
    // IF the target POS tag is CCONJ set the deprel to @cc [88%]
    // IF the target POS tag is SCONJ set the deprel to @mark [86%]
    // IF the target POS tag is DET set the deprel to @det [83%]
    // TODO: Put this somewhere better
    if(thisToken['upostag'] in POS2RELmappings) {
        sentAndPrev = changeConlluAttr(sent, indices, "deprel", POS2RELmappings[thisToken['upostag']])
    }

    var validDep = true;
    if(thisToken['upostag'] == 'PUNCT' && !is_projective_nodes(sent.tokens, [destIndex])){
        validDep = false;
        console.log('WARNING: Non-projective punctuation');
    }
```

Should probably go somewhere else. e.g. (1) relation prediction (2) validation.

**Comment by jonorthwash** [comment]
What about combining the keyboard shortcut handling functions?  The method lower in the file is probably better in some ways, but let's do it in whatever the current best practices are.

**Comment by keggsmurph21** [comment]
this was massively refactored over the past few weeks
