### ISSUE TITLE
refactor visualiser.js

### ISSUE THREAD

**Issue by maryszmary** [jonorthwash/ud-annotatrix#184]
- [ ] make the code more readable and consistent:
  - [ ] get rid of commented out lines which don't help in understanding of the code
  - [ ] split up long functions into smaller ones
  - [ ] make variable names self-expanatory
- [ ] get rid of redundant code
- [ ] get rid of unnecessary global variables
- [ ] write a doc-string for every function

**Comment by keggsmurph21** [comment]
this file no longer exists :)
