### ISSUE TITLE
Don't re-position graph after updating deprel labels

### ISSUE THREAD

**Issue by kristiank** [jonorthwash/ud-annotatrix#186]
The behaviour now is such that every time I update a deprel's label, then the graph is re-positioned on the screen. This is very annoying when working with long sentences and I need to repeatedly drag the graph towards the end I am currently working on.

**Comment by kristiank** [comment]
The re-position is triggered also by deleting or adding a deprel, also here the behaviour of re-positioning should be eliminated. Re-drawing of the graph should always take the previous position's coordinates.

**Comment by ftyers** [comment]
Check c61fe0d, it should be fixed. @maryszmary could you check it and update your installation on GitHub pages if it seems to work ?

**Comment by kristiank** [comment]
Seems fixed. Though re-sizing the browser window triggers an odd repositioning.
