### ISSUE TITLE
space shouldn't cause weirdness with NaN and going to the end of the textarea

### ISSUE THREAD

**Issue by KatyaAplonova** [jonorthwash/ud-annotatrix#188]
When you are editting a comment in the textarea ,for example ```# labels = blah foo``` then the cursor goes to the end of the text area. and makes a newline for every character. this is non-optimal and should be fixed.

**Comment by jonorthwash** [comment]
Is this a duplicate of #129?

**Comment by keggsmurph21** [comment]
old, closing
