### ISSUE TITLE
Loading button and progress indicator

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#19]
Instead of just automatically starting to upload when a file is chosen, have a button that says "upload" (or "load"). There should also be some indicator showing the progress of the upload.

**Comment by rueter** [comment]
At the moment, I am able to browse and select a file. The file name is even shown, but there seems to be no way to access the file, which, by the way, is in CoNLL-U format.

**Comment by jonorthwash** [comment]
> there seems to be no way to access the file

What do you mean?
