### ISSUE TITLE
interface for adjusting tokenisation in graph

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#2]
Make a way to adjust the tokenisation of elements of a UD graph.  This should allow you to divide existing tokens, combine existing tokens, reorder existing tokens, split a token into subtokens, insert tokens, and delete tokens, and renumbering should be automatic.

Keyboard shortcuts should be involved, but mouse actions too, suck as clicking and dragging across an element that should be split from another element before hitting the "split" key or something.

**Comment by ftyers** [comment]
so imagine you have

```
thisisatest.
```
you click on `(t, 0)` hold down click and drag to `(s, 3)` and let off click

this makes:

```
this isatest.
```
now you click on `(i, 5)` and hold down click and drag to `(s, 6)`, which makes

```
this is atest.
```

etc. until all the list is properly surface-tokenised.

**Comment by jonorthwash** [comment]
But you'd have to enter "tokenise" mode, and then leave it when done.  And you'd need a similar way to e.g., combine existing tokens, which has two subtypes: merge tokens, and merge and create subtokens.

**Comment by jonorthwash** [comment]
Basic interface:
- select content (e.g., across tokens), press key combo A to merge/split tokens
- select content (e.g., within a token), press key combo B to merge/split subtokens/"words"

Will need to include:
- logic for renumbering; one option:
  - Say nodes 8 and 9 are merged.  Renumber all nodes above 9, subtracting one, and keep track in a hash of mapping from old to new.  Then go through all targets and renumber according to hash.

**Comment by maryszmary** [comment]
At the moment the interface supports splitting a token into new ones. To split a token, click the right button of the mouse on the token node, then (using arrows) go to the place you want to split and insert a space, then press `enter`. All the attributes default to belong to the first part.

An illustration. Before:
![image](https://user-images.githubusercontent.com/16348652/29007830-3c705ada-7b14-11e7-8242-1ecb71cfb10a.png)
After:
![image](https://user-images.githubusercontent.com/16348652/29007833-4857b41a-7b14-11e7-84ea-d883c690c452.png)

So far the positioning of the input element is not ideal, I'm going to improve it.

**Comment by jonorthwash** [comment]
Nice!  Can tokens be merged too, or not yet?

**Comment by maryszmary** [comment]
Not yet.

**Comment by maryszmary** [comment]
Now they can. Here is how it can be made:
Left click on the main token (the token you want to take the markup from), then press `m`, then select with an arrow (right or left), which neighbor you want to append to the main token.

An example: left click on the token, then `m`
![image](https://user-images.githubusercontent.com/16348652/29083783-876dd29c-7c72-11e7-811c-3457ec4a4ce3.png)

I press the right arrow which token i want to append
![image](https://user-images.githubusercontent.com/16348652/29083831-b18692d0-7c72-11e7-9b80-d22a34ee0aa1.png)

**Comment by jonorthwash** [comment]
Cool!

**Comment by jonorthwash** [comment]
This is the basic functionality for this issue.  We'll open a new issue for subtoken-related functionality.
