### ISSUE TITLE
Words in all caps sometimes overflow 

### ISSUE THREAD

**Issue by JPJPJPOPOP** [jonorthwash/ud-annotatrix#200]
![screen shot 2017-12-29 at 11 36 12 am](https://user-images.githubusercontent.com/13565154/34446028-d71ad1d4-ec8c-11e7-9efe-827733af0680.png)
As you can see, SENTENCE is overflowing a little bit, and CAPS is very close to the edges.

![screen shot 2017-12-29 at 11 32 44 am](https://user-images.githubusercontent.com/13565154/34446010-bd5928d6-ec8c-11e7-963d-afe7fd85726e.png)
WANNA is overflowing quite a bit.

**Comment by JPJPJPOPOP** [comment]
@ftyers Reopen due to #226?

**Comment by Androbin** [comment]
@JPJPJPOPOP Sorry about the drama #242.
