### ISSUE TITLE
Select deprel title text when clicked

### ISSUE THREAD

**Issue by kristiank** [jonorthwash/ud-annotatrix#203]
When clicking a deprel for opening the title text editor, the text in the edit box should be selected. This would enable the user to rename the deprel without first needing to select the text.

**Comment by gstark0** [comment]
hmmm... Seems like it's working but not for all browsers, this works for Safari.

**Comment by kristiank** [comment]
... does not work on Firefox 47.0.

**Comment by kristiank** [comment]
If it can be confirmed that it works on later Firefoxes, this could be closed with a wontfix for as much as I am concerned.

**Comment by gstark0** [comment]
Nope, I just checked it on Chrome, doesn't work, maybe it's just built in safari feature.

**Comment by kristiank** [comment]
I know it is possible to select (or is mark the correct word it?) text with JavaScript. But maybe Safari does this by itself.
