### ISSUE TITLE
Children of "case" is marked red

### ISSUE THREAD

**Issue by kristiank** [jonorthwash/ud-annotatrix#215]
Of some unknown reason children (at least of deprel type *conj*) are marked with a red arc.
![red arc](https://user-images.githubusercontent.com/1181113/34894834-9ee04758-f7eb-11e7-8640-5e70640ba6a6.png)

**Comment by ftyers** [comment]
It should be fixed in 8245b10. Could you check ?

**Comment by kristiank** [comment]
Yes. In my sentence the ``conj`` is no longer marked with red.
