### ISSUE TITLE
Can't convert plain text to Conllu after adding 2nd sentence

### ISSUE THREAD

**Issue by gstark0** [jonorthwash/ud-annotatrix#222]
If you add 2nd sentence to ud-annotatrix by clicking the add button, after writing the sentence in text area, clicking on the Conllu tab doesn't work. Simply nothing happens. You have to paste text in conllu format to generate the graph.

**Comment by diogoscf** [comment]
Probably due to the same bug as in #144.

**Comment by gstark0** [comment]
@diogoscf You're right, thanks for clarify. Will close.
