### ISSUE TITLE
Offset mouse click after input resize

### ISSUE THREAD

**Issue by JPJPJPOPOP** [jonorthwash/ud-annotatrix#229]
Resizing the input area at the top makes mouse clicks in the cytoscape offset.
![offsetmouseclick](https://user-images.githubusercontent.com/13565154/34921162-4836d4dc-f933-11e7-8dd1-50b2c291d782.gif)

**Comment by jonorthwash** [comment]
Duplicate of #119.

**Comment by keggsmurph21** [comment]
closing, duplicate
