### ISSUE TITLE
passing text via uri

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#23]
Add support for up to one sentence (annotated or not) as a variable in the uri that gets thrown into the textbox and then parsed.  Could be very useful for demo purposes.

**Comment by maryszmary** [comment]
After 5d3340c633a22e8180273960aebe9195205a1dca, it takes text from url, but doesn't generate any kind of visualization for it at once. It does generate the tree after some time or when you start editing the text in the textbox though.

**Comment by maryszmary** [comment]
Fixed tree generation in 913ed7d65f70a65e1aee06480f6d7dc57ec18fa8.
