### ISSUE TITLE
Copy and pasting into input box doesn't convert to conllu correctly

### ISSUE THREAD

**Issue by JPJPJPOPOP** [jonorthwash/ud-annotatrix#233]
Copying and pasting anything into the input box then clicking the conllu tab causes this to happen:
![screen shot 2018-01-15 at 12 12 33 am](https://user-images.githubusercontent.com/13565154/34932727-f2108412-f988-11e7-976a-4e638be7cd8f.png)

**Comment by ftyers** [comment]
What did you copy and paste in ?

**Comment by JPJPJPOPOP** [comment]
Oh lol, the new code broke this oops.
