### ISSUE TITLE
clean up current .html file

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#24]
Take all javascript from .html out, put in a separate library to be included, clean up code a bit (indentation, style, etc.)

**Comment by maryszmary** [comment]
Done by @MidasDoas. I have moved body.load.js from ./lib/ext/ to ./lib/, as it is not an external library, but local code.

**Comment by maryszmary** [comment]
Cleaned up in 5d3340c633a22e8180273960aebe9195205a1dca.
Changed the location of body.load.js in 68de8b39d3eeffe3af084c9bbd4eff51620bb75c.
