### ISSUE TITLE
Add collaborative functionality like PiratePad

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#241]
PiratePad/Etherpad are pretty cool they let multiple people edit the same thing at the same time.  This would be great to have for collaborative annotation. There is a javascript library that does it: https://togetherjs.com/

Perhaps we could use it for annotatrix also ?

**Comment by gstark0** [comment]
I'm interested in implementing this! But this wouldn't work on localhost right?

**Comment by gstark0** [comment]
@ftyers Hmm im working on it right now, but it seems I would need to rewrite some functions to be called specifically for TogetherJS? As it needs to send and receive data? (if it's in the same function, then it's looped, and it updates consistently)

**Comment by gstark0** [comment]
@ftyers I think the best idea will be to just create new .js file for this, and make rewrite all necessary functions there. Do you agree?

**Comment by ftyers** [comment]
@gstark0 check with @maryszmary before adding stuff to `annotator.js`. What would you like to add ?

**Comment by jonorthwash** [comment]
I believe this has been implemented by @keggsmurph21.  If it's not what was intended by this issue, feel free to reopen.  If there are problems with it or missing features, feel free to open new issues for those.
