### ISSUE TITLE
Nodes are too little for its labels

### ISSUE THREAD

**Issue by gstark0** [jonorthwash/ud-annotatrix#247]
Problem with #242 
<img width="395" alt="screen shot 2018-01-16 at 16 14 58" src="https://user-images.githubusercontent.com/25964807/34996002-85ef5118-fad8-11e7-8e0a-35be3b5b28d6.png">

**Comment by jonorthwash** [comment]
Did this ever get solved?  I thought it did, but I'm still getting errors.  @Androbin 

![selection_034](https://user-images.githubusercontent.com/963849/35353221-7e234f88-0114-11e8-9f58-1e5a604a738e.png)

**Comment by Androbin** [comment]
Could you try with the last version before that change and post a screenshot?

**Comment by Androbin** [comment]
Do you get the same or different results for the example sentence used?
https://github.com/jonorthwash/ud-annotatrix/pull/219#issuecomment-357449634

**Comment by Androbin** [comment]
I can't reproduce your issue.

**Comment by Androbin** [comment]
Seems like #251 reverted my changes.

**Comment by gstark0** [comment]
@jonorthwash Actually I fixed it in #251 :)

**Comment by Androbin** [comment]
@gstark0 Your PR basically got us back to the original formula which didn't work.

**Comment by gstark0** [comment]
@Androbin Nope. It does work (you can see screenshots I attached there  ;))

**Comment by Androbin** [comment]
@jonorthwash said it in #226 and I'll say it again: No hardcoding!

**Comment by gstark0** [comment]
@Androbin My answer in #251

**Comment by Androbin** [comment]
Failed to reproduce with 975c318bf24e760e7dfe6b047323334581b2080d:
![screenshot](https://user-images.githubusercontent.com/16437156/35355578-022409a6-014e-11e8-874b-5e9e3ef469bd.png)

**Comment by gstark0** [comment]
@Androbin That is weird because, I can reproduce it (I'm actually not the only one who noticed it):
<img width="582" alt="screen shot 2018-01-24 at 21 49 09" src="https://user-images.githubusercontent.com/25964807/35356379-889ee0b2-0150-11e8-8b60-0451e851114a.png">

**Comment by Androbin** [comment]
@gstark0 Have you checked out the very same commit?

**Comment by gstark0** [comment]
Yes.

**Comment by Androbin** [comment]
@gstark Does this happen with Safari or with other browsers as well?
Could you check what value `1rem` resolves to?

**Comment by gstark0** [comment]
@Androbin Sure, I will check this when I get back home :)
