### ISSUE TITLE
Normalize behaviour of "pressing enter" when changing labels

### ISSUE THREAD

**Issue by kristiank** [jonorthwash/ud-annotatrix#248]
Now two behaviours exists:
1. when changing the label of a deprel, pushing enter selects from the dropdown menu and exits the label-editing-mode.
1. when changing the label of a POS, pushing enter selects from the dropdown menu, but doesn't exit from the label-editing-mode.

I think one of the behaviours should apply consistently for both cases. (Which one? I don't mind any of them.)

**Comment by Zensho** [comment]
Currently it seems that both cases work like case 1 already, where enter exits the label-editing-mode. Please let us know if the problem persists and is able to be replicated.
