### ISSUE TITLE
make more compliant with CG

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#25]
Implement more CG-compliant CG parsing in visualise.js.

**Comment by maryszmary** [comment]
Still needs debugging: in cases of some malformated trees indices shift, which causes a mess. E.g. in an example below lack of analyses for the first comma causes indices shift:
![image](https://user-images.githubusercontent.com/16348652/27358827-1f74df5e-5621-11e7-84fa-75d7b18341f4.png)

I'm going to refactor and debug it a little later.

**Comment by maryszmary** [comment]
BTW @jonorthwash, why is the file visualise.js called so, given that the **only** thing it contains is a function which converts CG to conllux? I thinks, it's quite confusing and it should be named something like "CG2conllux.js". Can I rename it?

**Comment by jonorthwash** [comment]
Yes, I agree.  Feel free to rename it.
