### ISSUE TITLE
buggy behaviour for cursor select of POS

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#255]
When POS is selected from the dropdown with the cursor, it doesn't update.  Then, when another node is selected, and the initial node is selected, and enter is pressed, the POS tag unexpectedly goes to the other node.  See screenshot:
![byzanz_2018-01-17_1358_new](https://user-images.githubusercontent.com/963849/35061773-344adef0-fb90-11e7-8084-59515f453451.gif)

**Comment by ftyers** [comment]
Might be related to #254

**Comment by jonorthwash** [comment]
This issue is half resolved.  See comments at PR #279.  Little effort is needed to finish it.

**Comment by keggsmurph21** [comment]
old
