### ISSUE TITLE
Problem visualizing CG3

### ISSUE THREAD

**Issue by d009** [jonorthwash/ud-annotatrix#264]
I tried to visualize an Estonian CG3 format file, but got no result. It seems that the problem is (at least partly) in tokens that are linked to themselves (e.g punctuation that is annotated this way). An example sentence that I was experimenting with (using Chrome on Ubuntu 16.04) looks like this:

```
"<s>"

"<Ei>"
	"ei" L0 V aux neg @NEG #1->2
"<taha>"
	"taht" L0 V main indic pres ps neg @FMV #2->0
"<nõustuda>"
	"nõustu" Lda V main inf @OBJ #3->2
"<sellega>"
	"see" Lga P dem sg kom @ADVL #4->3
"<,>"
	"," Z Com CLB #5->5
"<kindel_piir/>"
	"####" L0 Z CLB #6->6
"<et>"
	"et" L0 J sub @J #7->11
"<inimene>"
	"inimene" L0 S com sg nom @SUBJ #8->11
"<vaid>"
	"vaid" L0 D @ADVL #9->10
"<kannatades>"
	"kannata" Ldes V main ger @ADVL #10->11
"<areneb>"
	"arene" Lb V main indic pres ps3 sg ps af @FMV #11->4
"<.>"
	"." Z Fst #12->12
"</s>"
```

**Comment by ftyers** [comment]
I think this isn't strictly valid CG because the "<s>" and the "</s>" look like wordforms but are not. In addition you have single node circular dependencies e.g. `#12->12`. 

What we should probably do is mark dependencies as unannotated if the parent is the same as the node itself.

**Comment by ftyers** [comment]
The second part of this bug should be fixed now in 27c9015.

![captura de 2018-01-24 12-02-18](https://user-images.githubusercontent.com/449545/35328992-7822e726-00fe-11e8-9846-621ee94bb516.png)

**Comment by ftyers** [comment]
@d009 how much would you like to be able to have those sentence markers, on a scale of 1&mdash;10 ?

**Comment by d009** [comment]
@ftyers It's no problem to convert those sentence markers, but that's what's currently in the Estonian treebank. Let's say 3. Thanks for the fix above!

**Comment by ftyers** [comment]
Ok, I'm going to close this for now, if there are more problems or if you change your mind, please file new issues :)
