### ISSUE TITLE
tree visualization

### ISSUE THREAD

**Issue by arademaker** [jonorthwash/ud-annotatrix#266]
Maybe https://bl.ocks.org/adamfeuer/042bfa0dde0059e2b288 would be nice to try!

**Comment by jonorthwash** [comment]
There was some reason we avoided d3.  @maryszmary, do you remember why we/you opted for the current system?

**Comment by maryszmary** [comment]
@jonorthwash, because it was quick and easy to learn... I do agree now, that d3js would be probably better, but changing the visualization lib would mean rewriting _a lot_ of code now. :(

**Comment by jonorthwash** [comment]
Okay, that makes sense.  Perhaps it would make sense as part of a GSoC project.

**Comment by maryszmary** [comment]
Perhaps. What would be the benefits of switching to d3js? I.e. what do we expect from it?

**Comment by arademaker** [comment]
@maryszmary more flexibility? I also expect from d3js better compatibility with many browsers given its popularity. Note: the interface above allows edition not only visualisation.

**Comment by keggsmurph21** [comment]
we've decided not to move in this direction (since cytoscape handles the difficult click-/keystroke-handling fairly nicely for us, and D3 doesn't), so i'm gonna go ahead and close this for now
