### ISSUE TITLE
Code box is way too big by default

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#273]
We need to adjust the size of the code box to the screen size. If there is no text in the box it shouldn't be massive by default.

![peek 2018-03-03 12-45](https://user-images.githubusercontent.com/449545/36933896-13f0fefe-1ee1-11e8-851b-099a17f1f323.gif)

**Comment by keggsmurph21** [comment]
defaulting `#indata`'s `height` to `20em` (in `standalone/lib/css/style.css`) should fix this ... see ce3310b
