### ISSUE TITLE
problem with download

### ISSUE THREAD

**Issue by KatyaAplonova** [jonorthwash/ud-annotatrix#275]
I cannot download an annotated corpus. I've used both online and offline, different browsers and connections, but it didn't help.
![screen shot 2018-03-10 at 8 55 04 am](https://user-images.githubusercontent.com/31896125/37238490-c6786eae-2440-11e8-9703-4cd873d0b8a3.png)

**Comment by renhongkai** [comment]
I cannot upload corpus.Can you use the upload function?

**Comment by keggsmurph21** [comment]
Should be fixed as of a3bab5ed7e354d17f9cec97034bb6c9738da0fd2.
