### ISSUE TITLE
Annotatrix doesn't work in Safari

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#276]
If you type text nothing happens.

**Comment by jonorthwash** [comment]
Could you add more information?  A screencast or a more thorough description might help.

**Comment by keggsmurph21** [comment]
![screen shot 2018-08-08 at 7 15 56 pm](https://user-images.githubusercontent.com/9888800/43869256-a44e90e4-9b3f-11e8-8eff-4e0f5f776203.png)
@jonorthwash and i were using it in safari today with no problems ... also screenshot proof attached :)
