### ISSUE TITLE
Problems with XPOSTAG detection

### ISSUE THREAD

**Issue by DanielSpecht** [jonorthwash/ud-annotatrix#28]
Sometimes the tool does not detect the XPOSTAG correctly. More precisely, our team fills the XPOSTAG column with the predictions made from a parser in order to give an idea to the annotators of the general structure of the sentence. For instance, the following sentence taken as having some errors an is not displayed:

```
# text = Tem sentido -- aliás, muitíssimo sentido.
# source = CETENFolha n=1 cad=Opinião sec=opi sem=94a &D
# sent_id = CF1-4
# id = 3
1	Tem	ter	VERB	<mv>|V|PR|3S|IND|@FS-STA	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	0	root	_	_
2	sentido	sentido	NOUN	<np-idf>|N|M|S|@<ACC	Gender=Masc|Number=Sing	1	obj	_	_
3	--	--	PUNCT	PU|@PU	_	1	punct	_	_
4	aliás	aliás	ADV	<kc>|ADV|@<ADVL	_	1	advmod	_	ChangedBy=Issue165|SpaceAfter=No
5	,	,	PUNCT	PU|@PU	_	7	punct	_	_
6	muitíssimo	muitíssimo	DET	<quant>|<SUP>|DET|M|S|@>N	Gender=Masc|Number=Sing|PronType=Ind	7	det	_	_
7	sentido	sentido	NOUN	<np-idf>|N|M|S|@N<PRED	Gender=Masc|Number=Sing	2	appos	_	ChangedBy=Issue165|SpaceAfter=No
8	.	.	PUNCT	PU|@PU	_	1	punct	_	_

```
When we remove the text in the XPOSTAG there are no errors displayed:
```
# text = Tem sentido -- aliás, muitíssimo sentido.
# source = CETENFolha n=1 cad=Opinião sec=opi sem=94a &D
# sent_id = CF1-4
# id = 3
1	Tem	ter	VERB	_	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	0	root	_	_
2	sentido	sentido	NOUN	_	Gender=Masc|Number=Sing	1	obj	_	_
3	--	--	PUNCT	_	_	1	punct	_	_
4	aliás	aliás	ADV	_	_	1	advmod	_	ChangedBy=Issue165|SpaceAfter=No
5	,	,	PUNCT	_	_	7	punct	_	_
6	muitíssimo	muitíssimo	DET	_	Gender=Masc|Number=Sing|PronType=Ind	7	det	_	_
7	sentido	sentido	NOUN	_	Gender=Masc|Number=Sing	2	appos	_	ChangedBy=Issue165|SpaceAfter=No
8	.	.	PUNCT	_	_	1	punct	_	_

```

I believe this is a bug. I have tested this same case in other UD tools and I have not encountered the same problem.

By the way I really appreciate your initiative in developing this tool, the UD teams are in need of this kind of resources.

Cheers!

**Comment by ftyers** [comment]
Hey there, yes this is a bug, we'll get on it asap. Is that the Eckhard's CG parser for Portuguese ? As a matter of interest, have you tried putting the info in the `MISC` column ?

**Comment by ftyers** [comment]
Ok, I couldn't find the root of the problem, but I've made a workaround to "fix" it for now and left a note in the code for it to be fixed properly. Can you test it and check it also "works" on your end ? If not I'll take another look.

**Comment by arademaker** [comment]
@ftyers yes it is the PALAVRAS tags from @EckhardBick. I don't like the idea to move these tags to MISC field since the use of the XPOSTAG field is not violating the CoNLL-U format specification. Note that the values `<` and `>` do not violate the constraints on this field as defined in http://universaldependencies.org/format.html

Thank you for fixing it. Can you point the commit that you produced? The idea would be to start collaborate with you in this project, having a good online editor of CoNLL-U files is one of our priorities.

**Comment by ftyers** [comment]
The commit is [here](https://github.com/jonorthwash/ud-annotatrix/commit/ed4045b56009a66521f6af2fea83995acf2b43a0#diff-576122e3b9578f0f32ab760599e35f52). It's not a good commit, but it gets around your immediate problem. Yes, I realise it doesn't violate the format, but for some reason the code is messing up at the moment. I don't know why, the use of `>` and `<` has a similar effect on other columns.  

We'd love more collaborators. :)

**Comment by arademaker** [comment]
@ftyers I didn't really understand the statement `The purpose of the UD Annotatrix is to provide interfaces to the current visualiser tool`  in the README. The code in this repo is a front end of another tool? Can we make the http://jonorthwash.github.io/visualise.html run on our own server?

**Comment by ftyers** [comment]
Yep, you can just clone the repo and navigate to the link. There is no backend code, it's all browser side. I don't know what that means in the repo either, we'll have to ask @jonorthwash  :)

**Comment by DanielSpecht** [comment]
I have taken a look into the solution and found something out.
The case I had posted in the first comment does not work yet.
BUT, after some digging i found out that the problem is the presence of the last "<" in the following lines:

- Second line with XPOSTAG = <np-idf>|N|M|S|@<ACC 
- Fourth line with XPOSTAG = <kc>|ADV|@<ADVL
- Seventh line with XPOSTAG = <np-idf>|N|M|S|@N<PRED

Removing the last "<" or closing it with a ">" (e.g. turning every "<" into a "<>") makes the errors disappear.

I will look into contributing to your project.

Cheers!

**Comment by vinit-ivar** [comment]
Chiming in - the original tree seems to work fine for me!

**Comment by arademaker** [comment]
works for me too. I suggest to close this issue. Maybe we can have another one to improve the solution.

**Comment by jonorthwash** [comment]
Yes, @arademaker, you can check out the code and run it anywhere—in theory locally on your own system.

**Comment by DanielSpecht** [comment]
Oh, sorry, I was testing it by http://jonorthwash.github.io/visualise.html which does not have the last version.

Yes, the commit worked! 
Thank you everyone for the help.

**Comment by jonorthwash** [comment]
I just updated http://jonorthwash.github.io/visualise.html — double check that that works?

**Comment by DanielSpecht** [comment]
@jonorthwash For me http://jonorthwash.github.io/visualise.html is working now.

**Comment by jonorthwash** [comment]
Cool; I'll close the issue then, but feel free to reopen it or file a new one if there are any related problems.  Thanks @ftyers for the quick "fix"!
