### ISSUE TITLE
merging incorrectly split tokens

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#281]
@EricaBiagetti has a problem with desupertokening supertokens. e.g. she has "[xxx yyy]", where [ ] shows a supertoken and she wants "xxxyyy" where the two constituent parts of the supertoken are merged.

In principle this should be possible by doing:

1. click on the supertoken
2. press delete
3. click on the token to the left that we want to merge right
4. press 'm'
5. press the right arrow.

But when we try and merge the resulting two tokens, the graph disappears:

![peek 2018-04-13 13-33](https://user-images.githubusercontent.com/449545/38732665-4d57a946-3f1f-11e8-9c8d-b833a17dafe4.gif)

The CoNLL-U tree is here: https://paste2.org/5yUxvHxG

**Comment by keggsmurph21** [comment]
fixed, see [attached](https://imgur.com/a/h4B7lO7)
