### ISSUE TITLE
set up testing

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#283]

**Comment by keggsmurph21** [comment]
check out the `Tester` class (instantiated as `window.test` or just `test`) in `/standalone/lib/tester.js`

to add a test, just create a property on the `Tester.tests` object of the form 
```javascript
myNewTest: () => { /* test logic goes here */ }
```

then to run the test, type in the console `test.run('myNewTest');` or just type `test.all()` to run all tests
