### ISSUE TITLE
add new empty CoNLL-U line on [enter] in textarea

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#285]
When editing raw CoNLL-U text, and a new line is needed, hitting [enter] seems the way to go.  But this results in weird behaviour.

So instead of getting a blank line, [enter] should result in a CoNLL-U formatted line with `_`s.  Line/token numbers should also be automatically updated.  This might be able to be implemented by just adding an empty token in the native UD storage format and synching/updating the CoNLL-U display.

There should be a similarly straightforward way to add a new line in table view as well.

**Comment by keggsmurph21** [comment]
fixed for `CoNLL-U` when `!IS_TABLE_VIEW`

**Comment by keggsmurph21** [comment]
fixed for `plain text` (everything except `CG3`) ... see a24bd41 and 43d8649

**Comment by keggsmurph21** [comment]
fixed for `CG3` ... see a88dffa, 29a5f46, 1c1e7f6
