### ISSUE TITLE
sentence length of 48?

### ISSUE THREAD

**Issue by rueter** [jonorthwash/ud-annotatrix#286]
annotatrix only seem to see as far as 48, and the validator I am using (python tools/validate.py --lang myv UD_Erzya-JR/not-to-release/myv-ud.conllu) only sees that far, as well.

https://paste2.org/wEL0mfPw

# sent_id = BryzhinskijMixail_Kirdazht_manu:3859
# text = Но зярс валгсь , зярс панжтнесь ды мекев парсте пекстнесь веле кенкшенть , кужо кенкшенть , куро кенкшенть ды эсест юртс совамо кенкшенть эрьва лисицянтень совицянтень те свал тейнема , кенкштне свал пекстазь улезт ; панжтнесызь келес ансяк валске марто ды чопоньбелев — ракшань ливтема совавтома шкане , куймесь таго стакалгадсь .
# text_en = But by the time he got down the hill, opened and closed the village gate, the lane gate, the cluster gate and the one to their own home (something everyone coming or going had to do, so the gates would always be closed; they were only opened in the morning and at dusk for taking out and letting in the cattle), the wicker of clay had grown heavy again.
# text_fi = Kun Ketšai tuli mäeltä alas, avasi ja sulki huolellisesti kyläveräjänsä, ??aukio/kenttäveräjän, kujaveräjän ja oman kotiveräjän, savikontti ehti taas alkaa painaa hänen selkäänsä. (Kaikkien kävijöiden tulee tehdä näin, jotta veräjät olisivat aina kiinni, veräjäthän pidetään selkosen selällään vain aamulla ja illansuussa, kun karjaa ajetaan laitumelle tai kotiin.)
1	Но	но	CCONJ	CC	_	3	cc	_	_
2	зярс	зярс	ADV	Adv|Der/Ill|Adv|Sem/Time	Derivation=Ill|AdvType=Tim	3	mark	_	_
3	валгсь	валгомс	VERB	V|Ind|Prt1|ScSg3	Mood=Ind|Number[subj]=Sing|Person[subj]=3|Tense=Prt1	55	advcl	_	SpaceAfter=No
4	,	,	PUNCT	CLB	_	6	punct	_	_
5	зярс	зярс	ADV	Adv|Der/Ill|Adv|Sem/Time	Derivation=Ill|AdvType=Tim	6	mark	_	_
6	панжтнесь	панжтнемс	VERB	V|Ind|Prt1|ScSg3	Mood=Ind|Number[subj]=Sing|Person[subj]=3|Tense=Prt1	3	conj	_	_
7	ды	ды	CCONJ	CC	_	10	cc	_	_
8	мекев	мекев	ADV	Adv|Lat|Sg|Nom|Indef	Case=Lat|Case=Nom|Definite=Ind|Number=Sing	10	advmod	_	_
9	парсте	парсте	ADV	Adv|Manner	AdvType=Man	10	advmod	_	_
10	пекстнесь	пекстнемс	VERB	V|Ind|Prt1|ScSg3	Mood=Ind|Number[subj]=Sing|Person[subj]=3|Tense=Prt1	3	conj	_	_
11	веле	веле	NOUN	N|Sem/Inanim_Cnt|Sg|Nom|Indef	Case=Nom|Definite=Ind|Number=Sing	10	obj	_	_
12	кенкшенть	кенкш	NOUN	N|Sem/Inanim_Cnt|Sg|Gen|Def	Case=Gen|Definite=Def|Number=Sing	11	goeswith	_	SpaceAfter=No
13	,	,	PUNCT	CLB	_	15	punct	_	_
14	кужо	кужо	NOUN	N|Sem/Inanim_Cnt|Sg|Nom|Indef	Case=Nom|Definite=Ind|Number=Sing	12	conj	_	_
15	кенкшенть	кенкш	NOUN	N|Sem/Inanim_Cnt|Sg|Gen|Def	Case=Gen|Definite=Def|Number=Sing	14	goeswith	_	SpaceAfter=No
16	,	,	PUNCT	CLB	_	18	punct	_	_
17	куро	куро	NOUN	N|Sem/Inanim_Cnt|Sg|Nom|Indef	Case=Nom|Definite=Ind|Number=Sing	12	conj	_	_
18	кенкшенть	кенкш	NOUN	N|Sem/Inanim_Cnt|Sg|Gen|Def	Case=Gen|Definite=Def|Number=Sing	17	goeswith	_	_
19	ды	ды	CCONJ	CC	_	23	cc	_	_
20	эсест	эсь	PRON	Pron|Refl|Pl3|Gen|Variant=Short	Case=Gen|Number=Plur|Person=3|PronType=Refl|Variant=Short	22	nmod	_	_
21	юртс	юрт	NOUN	N|Sem/Inanim_Cnt|SP|Ill|Indef	Case=Ill|Definite=Ind|Number=Plur,Sing	20	case	_	_
22	совамо	совамо	NOUN	N|IV|Sg|Nom|Indef	Case=Nom|Definite=Ind|Number=Sing|Valency=1	23	compound	_	_
23	кенкшенть	кенкш	NOUN	N|Sem/Inanim_Cnt|Sg|Gen|Def	Case=Gen|Definite=Def|Number=Sing	12	conj	_	_
24	(	(	PUNCT	PUNCT	_	29	punct	_	SpaceAfter=No
25	эрьва	эрьва	DET	Det|Sg|Nom|Indef	Case=Nom|Definite=Ind|Number=Sing	26	det	_	_
26	лисицянтень-совицянтень	лисицят-совицят	NOUN	N|V|NomAg|Sg|Dat|Def	Case=Dat|Definite=Def|Derivation=NomAg|Number=Sing	29	obl	_	_
27	те	те	PRON	Pron|Dem|Sg|Nom|Indef	Case=Nom|Definite=Ind|Number=Sing|PronType=Dem	29	nsubj	_	_
28	свал	свал	ADV	Adv|Tot|Sem/Time_dur	PronType=Tot|PronType=Tot	29	advmod	_	_
29	тейнема	тейнемc	VERB	V|TV|Oblig|Clitic=Cop|Prs|ScSg3	Valency=2|VerbForm=Oblig|Clitic=Cop|Number[subj]=Sing|Person[subj]=3|Tense=Pres	3	parataxis	_	SpaceAfter=No
30	,	,	PUNCT	CLB	_	33	punct	_	_
31	кенкштне	кенкш	NOUN	N|Sem/Inanim_Cnt|Pl|Nom|Def	Case=Nom|Definite=Def|Number=Plur	34	nsubj	_	_
32	свал	свал	ADV	Adv|Tot|Sem/Time_dur	PronType=Tot|PronType=Tot	33	advmod	_	_
33	пекстазь	пекстамс	VERB	V|Der/Озь|Ger	Derivation=Ozj|VerbForm=Conv	29	ccomp	_	_
34	улезт	улемс	AUX	V|IV|Opt|ScPl3	Mood=Opt|Number[subj]=Plur|Person[subj]=3|Valency=1	33	cop	_	SpaceAfter=No
35	;	;	PUNCT	CLB	_	29	punct	_	_
36	панжтнесызь	панжтнемс	VERB	V|Ind|Prs|ScPl3|Obj3	Mood=Ind|Number[subj]=Plur|Person[subj]=3|Tense=Pres|Obj3	29	conj	_	_
37	келес	келес	ADV	Adv	Adv	36	advmod	_	_
38	ансяк	ансяк	ADV	Adv	Adv	39	advmod	_	_
39	валске	валске	NOUN	N|Sg|Nom|Indef	Case=Nom|Definite=Ind|Number=Sing	36	obl	_	_
40	марто	марто	ADP	Adp|Po	AdpType=Post	39	case	_	_
41	ды	ды	CCONJ	CC	_	42	cc	_	_
42	чопоньбелев	чопоньбелев	ADV	Adv|Lat	Case=Lat	39	conj	_	_
43	—	—	PUNCT	CLB	_	46	punct	_	_
44	ракшань	ракша	NOUN	N|Sem/Anim_Cnt|SP|Gen|Indef	Case=Gen|Definite=Ind|Number=Plur,Sing	45	nmod:gobj	_	_
45	ливтема-совавтома	ливтема-совавтома	NOUN	N|Sg|Nom|Indef	Case=Nom|Definite=Ind|Number=Sing	36	nmod	_	_
46	шкане	шка	NOUN	N|Sem/Time|SP|Temp|Indef	Case=Temp|Definite=Ind|Number=Plur,Sing	39	conj	_	SpaceAfter=No
47	)	)	PUNCT	PUNCT	_	29	punct	_	SpaceAfter=No
48      ,       ,       PUNCT   CLB     _       29      punct   _       _
49      куймесь куйме   NOUN    N|Sem/Inanim_Cnt|Sg|Nom|Def     Case=Nom|Definite=Def|Number=Sing       51      nsubj   _       _
50      таго    таго    ADV     Adv|Sem/Time    AdvType=Tim     51      advmod  _       _
51      стакалгадсь     стакалгадомс    VERB    V|Ind|Prt1|ScSg3        Mood=Ind|Number[subj]=Sing|Person[subj]=3|Tense=Prt1    0       root    _       SpaceAfter=No
52      .       .       PUNCT   CLB     _       51      punct   _       _

**Comment by rueter** [comment]
The last constituent visible is 47, and, of course, there is also the problem of not being able to see or edit the deprels  of this length of sentence very well in horizontal mode, but that is probably attributed to another issue. (Could someone point to the appropriate issue, please?)

**Comment by keggsmurph21** [comment]
should be fixed on branch `km` ??

@rueter can you please reopen if this is still an issue

**Comment by rueter** [comment]
I want to reopen this issue #286
At the moment, the master version does not show the entire tree; only as far as 47 of of 52. The km branch only has a whiteout when using a stand-alone version on firefox (52.7.3) and google chrome (66.0.3).

**Comment by keggsmurph21** [comment]
@rueter 

closed for `master` branch (see 44d7b16) ... the issue was that your code had mixed tabs and spaces so the whitespace cleaning was getting aborted
