### ISSUE TITLE
In long sentences distance between arrows is too large

### ISSUE THREAD

**Issue by KatyaAplonova** [jonorthwash/ud-annotatrix#289]
When there is a long sentence, sometimes, distance between arrows is too large and one can't see all deprel on the screen.
![screen shot 2018-05-29 at 6 32 11 pm](https://user-images.githubusercontent.com/31896125/40669058-b5cda1c4-636e-11e8-90a2-facd1e572e09.png)

**Comment by ftyers** [comment]
@KatyaAplonova could you paste the conllu here?

**Comment by KatyaAplonova** [comment]
conllu: https://paste2.org/faj1J8N1

**Comment by ftyers** [comment]
@keggsmurph21  in the `km` branch is better, no sense in doing the work twice.

**Comment by jonorthwash** [comment]
> in the `km` branch is better, no sense in doing the work twice.

It would be good to merge it with `master`, though...  I don't see how doing that constitutes doing work twice.

**Comment by jonorthwash** [comment]
Duplicate of #161.
