### ISSUE TITLE
preserve the imported filename to use it as the default exported filename

### ISSUE THREAD

**Issue by arademaker** [jonorthwash/ud-annotatrix#29]
If we preserve the filename in the import, we can use it as default for export.

**Comment by maryszmary** [comment]
Done in commit c66f608b4402648de70f1023f28f08a5f1ded905. Now works like this (the current version on https://maryszmary.github.io/ud-annotatrix/visualise.html):
![image](https://user-images.githubusercontent.com/16348652/27517235-d997e77e-59d1-11e7-8ac3-a8da229ac238.png)
![image](https://user-images.githubusercontent.com/16348652/27517257-314a84c2-59d2-11e7-8182-0bdf581c4efd.png)
