### ISSUE TITLE
Do not get fonts from the internet in standalone mode

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#291]
When you're sitting in a café with 1G wifi... it's kind of annoying to get the fonts fetched from Google, it increases the load time by about a minute :(

**Comment by keggsmurph21** [comment]
is this a new problem? I didn't change font retrieval stuff in the `css`. i tried following the font resolution stuff, but it opened up into a giant rabbit hole pretty quickly.

i can follow it down, but before digging all the way in, i was just wondering if you had a quick fix in mind

**Comment by ftyers** [comment]
Just comment out the font retrieval in the css ?

**Comment by keggsmurph21** [comment]
ok, i wasn't sure if we needed those fonts or not

commented them out in 77f2c00
