### ISSUE TITLE
Improve default plain text tokeniser

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#292]
Fails on simple stuff like parentheses and numerals separated by comma.

"Дәүләтләрнең, шул исәптән Русиянең дә, диңгез чикләре ярдан 12 миль (яки 22,2 км) ераклыкта узуы килешенгән"

**Comment by keggsmurph21** [comment]
this was just a regex issue ... fixed now

relevant commits:
2447b51
99a1dd3
