### ISSUE TITLE
Icons broken in new version

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#293]
See:

![captura de 2018-07-13 16-59-17](https://user-images.githubusercontent.com/449545/42698437-3320ab36-86be-11e8-8c7e-46407e5ec4a8.png)

**Comment by keggsmurph21** [comment]
yeah I was talking with @jonorthwash about this, not sure why it happens

on the server version, it works fine for some reason

i'm finishing up the label stuff, but this can be next priority once that is done

**Comment by keggsmurph21** [comment]
fixed,see 1d06460
