### ISSUE TITLE
Remove "welcome" text

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#294]
We don't need the welcome text, perhaps a tooltip over the text entry window saying "paste text or conllu or vislcg formatted text here" but nothing in the text box by default, or at least text that goes away when you click on it.

![captura de 2018-07-13 16-59-17](https://user-images.githubusercontent.com/449545/42698508-6437bf16-86be-11e8-9ef7-94b838798ac5.png)

**Comment by keggsmurph21** [comment]
removed it, added a placeholder text (see 5ab635b)

**Comment by keggsmurph21** [comment]
FYI, this commit actually includes some changes that are going to be merged into master in the next few days (all the stuff inside `#label-container`) ... i can delete this or leave it, shouldn't really be an issue

**Comment by keggsmurph21** [comment]
nevermind, got rid of it in 77f2c00
