### ISSUE TITLE
issues with labels

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#296]
- [x] When a label that already exists is typed into the "new label" box and enter is pressed, it shouldn't add it.
- [x] When a label is clicked on, it should add/remove it from the current issue (like the "has label" checkbox currently does—and that can probably be removed.)
- [ ] Entire label interface can be made smaller.

**Comment by keggsmurph21** [comment]
- [ ] editing a label's name to an existing name produces funky behavior

**Comment by keggsmurph21** [comment]
\# 1 fixed in 565f016

**Comment by keggsmurph21** [comment]
so clicking a label should toggle it from being in the comments, rather than toggling it as a filter?

**Comment by keggsmurph21** [comment]
assuming the answer to this^ is yes, # 2 fixed in 91bed47

**Comment by keggsmurph21** [comment]
\# 3 addressed a bit in 2246bfc, could probably do more (`font-size`, maybe put the label bar somewhere else like GitHub's on the right)

**Comment by ftyers** [comment]
@keggsmurph21  screenie?

**Comment by keggsmurph21** [comment]
![screenshot_2018-07-17 ud annotatrix](https://user-images.githubusercontent.com/9888800/42846081-db799a20-89e5-11e8-97b4-5da4b55fea41.png)

**Comment by keggsmurph21** [comment]
\# 4 fixed in e69b221

**Comment by keggsmurph21** [comment]
added the ability to hide the labels interface altogether, so i'm going to go ahead and close this
