### ISSUE TITLE
"upload" greyed out in standalone version

### ISSUE THREAD

**Issue by keggsmurph21** [jonorthwash/ud-annotatrix#297]

**Comment by keggsmurph21** [comment]
this is expected behavior because there's nothing to upload to, right?

**Comment by jonorthwash** [comment]
Shouldn't it behave like an "import" function?  I.e., you might want to load your conllu file (or similar) into the interface to work on it, even without a backend running.

**Comment by coltekin** [comment]
Just another note that this is an important issue, at least for my workflow where I use ud-annotatrix as a local CoNLL-U editor on my browser, do (want to) not run any server.

**Comment by ftyers** [comment]
@coltekin @jonorthwash I agree. It 100% needs to be possible to (up)load conllu files into the interface from the local machine even when the server is not running.

**Comment by yaskevich** [comment]
By last commits of #356 upload functionality of static version was fixed. And it was not only greyed button.
