### ISSUE TITLE
interface for specifying a dependency relation

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#3]
Make a way of labelling a dependency relationship between two tokens after they have been linked.  Make sure that it can be controlled from the keyboard and using a mouse.

**Comment by ftyers** [comment]
This comment was in #38, which was closed, so I'll repeat it here:

When you make a new arc, you should have the opportunity to specify a dependency relation at the same time. The way I think it should work is as follows:

    You click on the head,
    A side bar appears with a complete list of the dependency relations where each relation has a hot key, like acl, advcl, amod -- they should be listed in alphabetical order of hot key.
    You click on the dependent
    You type the letter of the hot key and the relation is added.

Open question: where does the focus stay: on the head or on the dependent ? If on the head, how do you move it to a new head?

@fginter, is this more or less how you described before?

**Comment by jonorthwash** [comment]
The way I imagine it working is:
1. You click on the head,
2. You click on the dependent,
3. The place for the label turns into a box with autocomplete,
4. You start typing the name of a relation, and relations starting with those characters appear in the dropdown (limit 3 or so),
5. You can finish typing, scroll down and press enter, or click on one of the dropdown items to specify the relation name.

I'm not sure there's an easy way to support both this and what @ftyers is proposing without it being a configurable option.

**Comment by jonorthwash** [comment]
Also, my steps 1 and 2 should be alternatively replaceable with this:
1-2. Click on an arc.

**Comment by maryszmary** [comment]
Hm, I should have read the discussion before implementing it...
For now, it works like this:
1) you click on arc
2) press the `i` key
3) a prompt appears requesting the user to type the dependency relation:
![image](https://user-images.githubusercontent.com/16348652/27520251-5ecd29e4-5a0f-11e7-94aa-56c414dde18e.png)

I agree, that prompt is not good, and it should be something like *the label turns into a box with autocomplete*.

**Comment by jonorthwash** [comment]
I've tested this and it's functional, but it would be good to have a more intuitive implementation.

**Comment by fginter** [comment]
Hi

Our system was:

1. click to focus on head
2. shift-click on dependent
3. dialog appears to select a relation, with keyboard shortcuts being heavily used
4. focus stays on head

I don't say this is the only truth. But this is what we did and it worked.

I think autocomplete might be tricky here because you might need to type many letters before getting to the one which differs. Also, beware of "obl" vs "obj" - maybe you can use them as your test case for usability. We found some obl vs obj errors in our parallel udv2 data. They look visually too similar when annotating fast. :)

F

**Comment by ftyers** [comment]
There is also "advcl" vs. "advmod" and "discourse" vs. "dislocated" not to mention the language-specific features (e.g. compound:lvc, etc.)

**Comment by jonorthwash** [comment]
I agree that for the speediest annotation, a series of shortcuts would be fastest.  But not everyone will use this tool this way.  Some people will want to be able to use it for a once-off annotation without having to learn a bunch of shortcuts.  I'd really like to see something that is both intuitive and allows for the speed you guys were able to get.

@fginter , could you provide us a list of all your keyboard shortcuts?

**Comment by fginter** [comment]
Shortcuts: 

* Dependency type shortcuts were configurable here: https://github.com/TurkuNLP/TDT_editor/blob/master/dtreebank/gui/depTypes.sd    ...the letter which follows the dot is the shortcut for that dependency type.

* Others (from the top of my head):
  * left/right arrow changes dependency direction
  * DEL deletes
  * !  marks dependency red for later inspection (adds a flag)
  * SPACE launches the dependency type choice dialog

...and there there was a bunch of special one-off functionality shortcuts. I'd need to dig these out of the source code, but probably those are not that interesting.

**Comment by maryszmary** [comment]
The way of editing deprel described here doesn't work anymore. Now it works like this: you click the right button on the edge, a textbox *somewhere near it* appears, completed with the previous label, you change the label and press `enter`.

The textbox looks like this:
![image](https://user-images.githubusercontent.com/16348652/29031561-5a8b6626-7b97-11e7-860d-4881cd1c8d99.png)
I still have problems with correct positioning and work on it.

![image](https://user-images.githubusercontent.com/16348652/29031604-8020aaae-7b97-11e7-8a92-864c838d7984.png)

**Comment by jonorthwash** [comment]
This has been implemented now, though some of the details are still not totally worked out.  New issues can be opened for those.
