### ISSUE TITLE
check issues addressed by updates and fixes from @MidasDoas

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#30]
[Several existing issues](https://wikis.swarthmore.edu/ling073/User:Twarner2/Final_project) were recently addressed by @MidasDoas and are available in [his repo](https://github.com/MidasDoas/ud-annotatrix).  These should be merged in to this repo and assessed for how well the solve the issues.

**Comment by jonorthwash** [comment]
See also the his pull request, #27, which now has conflicts.

**Comment by MidasDoas** [comment]
I fixed the conflicts from #27 and believe I have submitted a pull request for the things left over from #27 (including URL decoding)

**Comment by maryszmary** [comment]
It seems, I've checked all the changes, namely, the changes discussed in #23, #24, #25 and #15.
#23, #24 and #15 are closed now, #25 needs further work.
