### ISSUE TITLE
reimplement graph validation

### ISSUE THREAD

**Issue by keggsmurph21** [jonorthwash/ud-annotatrix#306]

**Comment by keggsmurph21** [comment]
implemented error highlighting if the dependency `is_leaf` or `is_cycle` @jonorthwash @ftyers are there other things to check for?

relevant commit: 86576f4

**Comment by ftyers** [comment]
@keggsmurph21 if a label / POS-tag is valid.

**Comment by keggsmurph21** [comment]
1410c27 adds checking to make sure that the deprel is valid

**Comment by keggsmurph21** [comment]
Hm I don't see any `node.error` selectors in the `cy-style.js` file ... Maybe I just missed it though (on mobile)

**Comment by keggsmurph21** [comment]
Also , when would we mark a dependency as `incomplete`

**Comment by ftyers** [comment]
@keggsmurph21 when it has head but no deprel.

**Comment by keggsmurph21** [comment]
Ah, right ok. I'll fix these tomorrow, mobile vi is a nightmare lol

**Comment by keggsmurph21** [comment]
Ah, right ok. I'll fix these tomorrow, mobile vi is a nightmare lol

**Comment by jonorthwash** [comment]
> mobile vi is a nightmare lol

You could also edit the code in browser on GitHub :-P

**Comment by keggsmurph21** [comment]
see 368780e
