### ISSUE TITLE
SVG export

### ISSUE THREAD

**Issue by keggsmurph21** [jonorthwash/ud-annotatrix#311]
the `canvas2svg` library doesn't integrate with `cytoscape`, so we'll probably need to find a workaround or do it ourselves (yikes)

**Comment by jonorthwash** [comment]
@JPJPJPOPOP, did you mention this now works?

**Comment by JPJPJPOPOP** [comment]
@jonorthwash Yes.

**Comment by JPJPJPOPOP** [comment]
https://github.com/jonorthwash/ud-annotatrix/commit/1797c3e7bdb9f2f2382fb4d3843bf90b085298bb
