### ISSUE TITLE
Make the trees visually editable

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#32]
It should be possible to adjust the dependencies by drag-and-drop.

**Comment by jonorthwash** [comment]
This appears to be a meta-issue of several previously existing issues.

**Comment by maryszmary** [comment]
Now it's possible to draw adjust dependencies at https://maryszmary.github.io/ud-annotatrix/visualise.html by click on the head followed by click on dependent node (it seems to me more convenient than drag-and-drop).
The option is now supported in CoNLL-U only.

The illustration of how it works:

1. here is a tree with disconnected 1st and 4th nodes:
![image](https://user-images.githubusercontent.com/16348652/27402009-e5e93764-56cd-11e7-9230-e5170905b7e3.png)

2. now I click on the supposed head. the head's color changes to dipper blue:
![image](https://user-images.githubusercontent.com/16348652/27402109-3761d286-56ce-11e7-845c-05149fe63ef4.png)

3. then I click on the supposed dependent:
![image](https://user-images.githubusercontent.com/16348652/27402144-50c10e72-56ce-11e7-90cf-9c750fd221a8.png)

If a user clicks  on the same node second time, nothing happens. If a user clicks on a node and 10 seconds pass, the node returns to the normal state.

**Comment by maryszmary** [comment]
(Ah, and yes, based on what we've discussed it's evident, but the text in the textbox above is synchronized with the changes).

**Comment by jonorthwash** [comment]
It keeps doing this to me:
![dependency grammar visualiser - chromium_008](https://user-images.githubusercontent.com/963849/27418488-530c54b0-573d-11e7-816a-5096e18d8f70.png)

**Comment by jonorthwash** [comment]
Also, I think what you did is technically issue #3 .

**Comment by maryszmary** [comment]
It's a bug of my conllu parser. Working on it.

**Comment by maryszmary** [comment]
Hm, if what I did is actually issue #3, then what exactly does this issue (#32) refer to?..

**Comment by ftyers** [comment]
I think this is looking pretty good so far. I think that moving arcs looks nice, but this is possibly faster, and more importantly it works now. :)

**Comment by maryszmary** [comment]
@jonorthwash, I've adapted a cool CoNLL-U parser from https://github.com/FrancessFractal/conllu to parse conllu input. Now it should work fine.

**Comment by jonorthwash** [comment]
Cool, seems to work much better now.  One thing, though: every now and then it seems to forget the first node I clicked on?  This is a minor bug and probably doesn't need to be investigated at this point.  Good work!

**Comment by jonorthwash** [comment]
So, what is done now is something like "interface for visually specifying an arc between two nodes".  Perhaps we should close this issue and add more specific functionality as new issues (though a lot of it already exists).

**Comment by maryszmary** [comment]
>  every now and then it seems to forget the first node I clicked on
I guess, it happens because of this:
> If a user clicks on a node and 10 seconds pass, the node returns to the normal state.

I did it on purpose, and I can remove it, if you think it's better without it.

**Comment by maryszmary** [comment]
> Perhaps we should close this issue and add more specific functionality as new issues (though a lot of it is already in existing issues).

Yes, I agree. "Make the trees visually editable" is not very specific (there're lots of specific issues in this direction), hence not really helpful for development of the system, and the description of the issue by @ftyers, if I get it right, is something that is done now.

**Comment by jonorthwash** [comment]
> > If a user clicks on a node and 10 seconds pass, the node returns to the normal state.
> 
> I did it on purpose, and I can remove it, if you think it's better without it.

If the node is highlighted when clicked on (as it currently is), then I don't think there should be a timeout.  The user will be able to tell that the node is selected.  I assume you can click a node again to unselect it?

**Comment by jonorthwash** [comment]
>  the description of the issue by @ftyers, if I get it right, is something that is done now.

I think it's half-done.  See #5 for the other half.

**Comment by maryszmary** [comment]
> I assume you can click a node again to unselect it?

Yes.
Ok, removed it.

**Comment by maryszmary** [comment]
> I think it's half-done. See #5 for the other half. (I.e., you can probably close this and do the other half as #5.)

Ok, so, now that I understand what #5 means, I'm closing this one.
