### ISSUE TITLE
Japanese text overspills in the box

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#324]
This is the case for both the old and new interfaces. We should make sure that all writing systems work.

![japud](https://user-images.githubusercontent.com/449545/46023963-1d37b000-c0e6-11e8-8fde-b02fd759d201.png)

**Comment by jonorthwash** [comment]
Part of this issue is figuring out how to make the boxes scale in a way that's sensitive to the text width—and not just some calculation based on number of characters.

**Comment by JPJPJPOPOP** [comment]
@ftyers Can you try now? The boxes should scale based on text width, so this shouldn't be a problem anymore.

**Comment by jonorthwash** [comment]
Is this confirmed okay now?  Could we see a screenshot?

**Comment by JPJPJPOPOP** [comment]
@jonorthwash I tried a variety of Japanese conllu files and they work fine.
![Screen Shot 2020-06-11 at 2 18 43 PM](https://user-images.githubusercontent.com/13565154/84440340-a8c0df80-abee-11ea-8aea-f41770370279.png)
![Screen Shot 2020-06-11 at 2 19 32 PM](https://user-images.githubusercontent.com/13565154/84440355-b0808400-abee-11ea-92b9-240f4696a832.png)

**Comment by ftyers** [comment]
This looks great!

**Comment by jonorthwash** [comment]
Indeed, that's beautiful!
