### ISSUE TITLE
Minor issues with table view

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#333]
- [x] Once the table view table has been resized, it doesn't resize automatically when the window size is adjusted.  If it's desired to keep the window a particular width, there could be a "lock size" feature, but in general the default should be to resize it on window resize even if it's previously been manually resized.
- [x] Text in column headers (including the "«" characters) can't be clicked to collapse/expand the column.  Text shouldn't block the collapse/expand feature.
- [x] When editing the contents of a cell, pressing Esc should probably keep the cell highlighted, but leave edit mode.  Currently it leaves table navigation entirely.
- [ ] There should be a keyboard shortcut for entering table view which should also enter table navigation mode (even if table view is already enabled).
- [x] Currently table navigation mode allows you to go into cells of collapsed columns, but does not highlight those cells.  It should highlight those cells (probably in a slightly different way than uncollapsed cells).
- [x] Related to the above, there should be a keyboard shortcut for expanding and collapsing the column of the currently highlighted cell.
- [x] Delete/backspace should clear the contents of a cell.

**Comment by diogoscf** [comment]
I’ll think about possible shortcuts.

> * [ ]  Currently table navigation mode allows you to go into cells of collapsed columns, but does not highlight those cells.  It should highlight those cells (probably in a slightly different way than uncollapsed cells).

Actually it does highlight the collapsed cells for me

**Comment by jonorthwash** [comment]
> Actually it does highlight the collapsed cells for me

Aha, it works in chromium for me.  So this is a firefox-specific bug I guess?

**Comment by jonorthwash** [comment]
The collapsing issues still seem to be present in firefox too—things are working a lot more nicely in chromium in general.

**Comment by diogoscf** [comment]
> Aha, it works in chromium for me. So this is a firefox-specific bug I guess?
I tested it in both. That’s really weird

**Comment by jonorthwash** [comment]
What version of firefox?  I'm running 60.0, it seems.

**Comment by diogoscf** [comment]
That issue was actually happening when the table got rebuilt (when `rebuild()` was called) but it happened in chrome and firefox for me...
Just in case the new commit doesn't fix the problem, I'm running 63.0.3

**Comment by jonorthwash** [comment]
So `shift`-`-` seems to do the trick?

**Comment by jonorthwash** [comment]
Or just `-`.

**Comment by diogoscf** [comment]
So which should the behaviour be?
1. If you try to enter text into a collapsed cell, nothing happens
2. If you try to edit a collapsed cell, the existing text appears so you can change it based on that

**Comment by jonorthwash** [comment]
Probably something like 2, except with the column expanding:
3. If you try to edit a collapsed cell, the column uncollapses and let's you edit normally.

**Comment by jonorthwash** [comment]
The shortcut `ctrl-alt-t` doesn't work for me; it's a window-manager-level shortcut.

**Comment by diogoscf** [comment]
What about `alt-t`?

**Comment by diogoscf** [comment]
Ok. It's now `alt-n`

**Comment by jonorthwash** [comment]
Closing this issue; remaining issues to #499.
