### ISSUE TITLE
Graph dependencies aren't well placed in RTL mode

### ISSUE THREAD

**Issue by diogoscf** [jonorthwash/ud-annotatrix#334]
See screenshot
![broken-rtl](https://user-images.githubusercontent.com/26374538/49035355-cec19300-f1b4-11e8-8376-d2a6a5703806.PNG)

**Comment by jonorthwash** [comment]
The exiting and entering nodes were placed better before the code was refactored this summer.  In fact, I don't know that I've noticed this particular problem.  It looks like two things got switched.  Basically, entering arcs (with the arrows) should go to the middle while exiting arcs should leave offset a bit on the side the dependent is closer to.  It looks like that latter calculation got switched.

**Comment by JPJPJPOPOP** [comment]
![fixdeprelrtl](https://user-images.githubusercontent.com/13565154/77242262-f0206c80-6bb9-11ea-97ee-301547a52044.gif)

**Comment by JPJPJPOPOP** [comment]
@jonorthwash 
> firespeaker: jjjppp: you need dependency arcs going the other direction
   firespeaker: jjjppp: towards the beginning of the sentence

The beginning of the sentence is now the right side since its rtl. So the dependencies should be going the right direction.

**Comment by jonorthwash** [comment]
> > 
> 
> The beginning of the sentence is now the right side since its rtl. So the dependencies are currently in the right direction.

I think you misunderstood.  I'd like to see an example like the one @diogoscf posted where arcs go towards the beginning of the sentence.  If you simply correct the example you posted (with `I` as a dependent of `love`), then that would demonstrate it.

**Comment by JPJPJPOPOP** [comment]
![Screen Shot 2020-03-22 at 10 26 04 PM](https://user-images.githubusercontent.com/13565154/77284543-29c1a800-6c8c-11ea-95bb-f3ba974ecf58.png)
@jonorthwash
