### ISSUE TITLE
create subtokens by typing space in a token

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#347]
It used to be the case that a token could be split into subtokens by right-clicking on the token and adding a space to it.  Now that simply adds a space to the token.

#53 may be related (or it may be superseded—needs to be checked).

**Comment by JPJPJPOPOP** [comment]
@jonorthwash This is fixed.

**Comment by jonorthwash** [comment]
Just for record-keeping, could you note the commit that it was fixed in?

**Comment by JPJPJPOPOP** [comment]
https://github.com/jonorthwash/ud-annotatrix/commit/02b71acad8760fb46994b65fc61e8de28925265a
