### ISSUE TITLE
token number display

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#349]
Currently token number display looks really bad:
![Screenshot from 2019-05-04 19-10-07](https://user-images.githubusercontent.com/963849/57185804-66cc5280-6ea0-11e9-8fb5-f6a471deaafb.png)

They overlap with other things a lot and sometimes it's confusing what they attach to.

There are ways to make it look better, e.g. this one that comes to mind:
![2019-05-04 mockup](https://user-images.githubusercontent.com/963849/57185887-89f80180-6ea2-11e9-8d6b-f1ee0336ec97.png)

(aside from the new off-center issue, which would also need to be resolved)

**Comment by JPJPJPOPOP** [comment]
The reason they overlap is because the spacing between the tokens doesn't actually take into consideration the number nodes, but just the form nodes.

**Comment by keggsmurph21** [comment]
@JPJPJPOPOP I assume you'll be tackling this with the SVG rendering updates?

**Comment by JPJPJPOPOP** [comment]
@keggsmurph21 Yes.
