### ISSUE TITLE
Add token numbers/ranges and word numbers to the graph visualisation

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#36]
Add token numbers/ranges and word numbers to the graph. Here is an example with both tokens and syntactic words:

```
1	Walê	walê	_	adv	_	2	advmod	_	_
2	dixuye	xuyan	_	vblex	iv|pri|p3|sg	0	root	_	_
3	ko	ku	_	cnjsub	_	5	mark	_	_
4	gelek	gelek	_	preadv	_	5	advmod	_	_
5	xemxwar	xemxwar	_	adj	pst	2	ccomp	_	_
6	e	bûn	_	vbcop	pri|p3|sg	5	cop	_	_
7	û	û	_	cnjcoo	_	5	cc	_	_
8	misîbetin	musîbet	_	n	m|pl|nom|ind	11	nsubj	_	_
9-10	lê	_	_	_	_	_	_	_	_
9	_	li	_	pr	_	10	case	_	_
10	_	ew	_	prn	dem|mf|sg|obl	11	nmod	_	_
11	qewimîne	qewimin	_	vblex	iv|narr|p3|pl	5	conj	_	_
12	.	.	_	sent	_	2	punct	_	_
```

**Comment by maryszmary** [comment]
I'm not sure I understand. What should it look like? Do you mean, add a new level for syntactic words?

**Comment by ftyers** [comment]
![imatge](https://user-images.githubusercontent.com/449545/27514478-02543c9e-598c-11e7-97ae-1f85df2d1c03.png)
 
Something like this, but with better alignment :D

**Comment by maryszmary** [comment]
So, there should be both numbers below words in the tree and a sentence with words enumerated?

**Comment by jonorthwash** [comment]
That sounds right.

By the way, it looks like the POS tags from the CoNLL-U aren't getting into the graph.  CG format supports this though.  Should I file a separate issue, or is this a quick fix?

**Comment by maryszmary** [comment]
> By the way, it looks like the POS tags from the CoNLL-U aren't getting into the graph. CG format supports this though.

They do:
![image](https://user-images.githubusercontent.com/16348652/27601728-02970be8-5b79-11e7-990f-46722656b3f8.png)

But it seems that UPOSTAGs only, not XPOSTAGs (in @ftyers's example, the UPOSTAG column is empty).

**Comment by jonorthwash** [comment]
Hm, I'm not sure I understand what the difference between those is.  Maybe if all UPOSTAGs are empty, XPOSTAGs could be displayed / edited instead?  (Again, I would make a separate issue.)

**Comment by jonorthwash** [comment]
Potential copy of #8.

**Comment by maryszmary** [comment]
Implemented the basic functionality. Now looks like this:
![image](https://user-images.githubusercontent.com/16348652/29169486-f17ced60-7ddc-11e7-8de9-d0a5004ba9f0.png)

**Comment by jonorthwash** [comment]
Do we still want numbers?

**Comment by ftyers** [comment]
Yes, because some of the keyboard shortcuts are going to be based on numbers.

**Comment by maryszmary** [comment]
Is it ok done this way?
![image](https://user-images.githubusercontent.com/16348652/29490578-456f54c6-8549-11e7-8005-0ea7132203e1.png)

**Comment by jonorthwash** [comment]
That'll do for now!  Seems to be working, so I'll close this issue.
