### ISSUE TITLE
Removing a corpus from a web-interface

### ISSUE THREAD

**Issue by yaskevich** [jonorthwash/ud-annotatrix#369]
It is impossible to delete a corpus from web interface.

**Comment by jonorthwash** [comment]
The trash can (/"rubbish bin") icon used to do this.  This is a regression.

**Comment by yaskevich** [comment]
Actually, no.
To begin with, one cannot just delete the corpus, for example, if some incorrect or unneeded file was uploaded. On main page corpora are listed, there is no way to easily get rid of them.

In some way, one can open corpus (but this way is bad UX), and there, you're right, the trash can button is presented. However, it is rather should be separate **_issue_**, because "discarding corpus" doesn't not **delete** the corpus, but makes it empty (the worst UX). So, if one uploads, let's say, 10 corpora and now wants to delete them, one can only make them all empty and have to see them listed on main page for the rest of life.

![you-cannot](https://user-images.githubusercontent.com/522902/60205394-bce2c400-9859-11e9-8ff5-255b98d0ed2a.jpg)

**Comment by yaskevich** [comment]
Fixed by last commits in #356. Pretty new main page.
