### ISSUE TITLE
two annotators on one treebank causes intermittent skips to beginning of treebank

### ISSUE THREAD

**Issue by ksteimel** [jonorthwash/ud-annotatrix#381]
If you have uploaded a CONLL-U corpus and have two annotators working on the same server with backend on the same treebank, the sentence that is displayed will randomly jump back to the first sentence in the treebank. 

It seems to be linked to the other annotator making a change to the treebank.

Some additional information: 
- neither annotator was editing sentence number 1 in the treebank
- using ssh port forwarding to access the server (shouldn't affect anything but just for clarity)

**Comment by kmurphy4** [comment]
Thanks for the bug report!  Agreed that this is definitely not the desired behavior :)

I'll try to reproduce this weekend and get back to you.

**Comment by ksteimel** [comment]
Thanks a lot!

**Comment by keggsmurph21** [comment]
@ksteimel I was able to reproduce this bug this morning and made [this patch](https://github.com/jonorthwash/ud-annotatrix/commit/15fd199b74a554afd9985ce2b0e8fef5ec803ff4).

Let me know if you're still having the same issue after `git pull`ing!  Thanks again for the report.

Happy annotating :)
