### ISSUE TITLE
undo history

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#39]
I keep finding myself wanting to undo my last change.  It would be really useful to keep a full undo history (or within a certain limit, like say 5 changes) and be able to step back and forward within it.

**Comment by ftyers** [comment]
Using the normal ctrl+z / ctrl+y would be good.

**Comment by jonorthwash** [comment]
And ctrl+shift+z as an alternative for ctrl+y.

**Comment by jonorthwash** [comment]
The way I currently envision this is something like a note saying "3 changes since last commit" just off one of the corners of the textbox and/or graph, and when clicked has a short dropdown listing something like:
 4→2
 5 <s>`@nmod`</s>`@dobj`
 8↛6
And a little [commit button](#4) at the bottom to save the changes.

**Comment by maryszmary** [comment]
Editing POS labels, editing deprels, drawing arcs and deliting arcs is now undoable and redoable.

**Comment by jonorthwash** [comment]
Cool.  Instead of having buttons, could we have `ctrl+z` and `ctrl+y`/`ctrl+shift+z`?

**Comment by jonorthwash** [comment]
It doesn't seem to remember the history when things are changed in the textbox.

**Comment by jonorthwash** [comment]
Remaining issues in #171.
