### ISSUE TITLE
Adding new comment line in conll causes cursor to move to end of conll

### ISSUE THREAD

**Issue by ksteimel** [jonorthwash/ud-annotatrix#393]
Currently, I'm running a ud-annotatrix server (with backend) and I'm having issues adding a comment to the beginning line of the conll-u text. I can get `#` typed at the beginning but then it immediately moves the cursor to the end of the conll text. 

Not a huge deal just a bit annoying when I'm trying to add notes about ambiguity etc.

**Comment by keggsmurph21** [comment]
Hey @ksteimel  , thanks for the bug report. I'll try to take a look at it over the weekend and get back to you.

**Comment by keggsmurph21** [comment]
@ksteimel let me know if 5d1ff25 fixes your issue!

Also, you can also just turn off the autoparsing feature if you find it's getting in your way :^) (see bottom-left of this screenshot)
![Screen Shot 2020-02-01 at 2 31 45 PM](https://user-images.githubusercontent.com/9888800/73598564-a2fc1480-44ff-11ea-86ef-b93dafeead36.png)
