### ISSUE TITLE
Ability to switch between presentation formats

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#40]
When I input text in CG, it should be possible to switch to CoNLL-U format when a CG sentence is fully disambiguated. The backend format should probably be CoNLL-U, as it supports slightly more than CG. So you'd take the,

```
"<«>"
	"«" lquot  
"<Кърал>"
	"кърал" n attr 
"<тил>"
	"тил" n nom  
"<»>"
	"»" rquot  
"<.>"
	"." sent  
```

And this would become in the CoNLL-U something like:

```
1    «          «            _  lquot   _   _   _  _   _   
2   Кърал  кърал   _   n     attr   _   _  _   _   
3   тил      тил        _   n      nom _   _  _   _   
4    »          »       _     rquot   _  _   _  _   _   
5    .           .        _     sent   _   _   _  _   _   
```

You should be able to switch back and forth between the two formats without losing anything, e.g.something like model = backend CoNLL-U and view = CG / CoNLL-U / sdparse.

Note that an undisambiguated sentence could not be converted,

```
"<официал>"
	"официал" adj
	"официал" adj subst nom
	"официал" adj subst px3sp nom
"<буксмол>"
	"букмол" n nom
	"букмол" n attr
	"букмол" n px3sp nom
"<бирча>"
	"бирча" adj
		"э" cop aor p3 pl
	"бирча" adj
	"бирча" adj subst nom
	"бирча" adj subst nom
		"э" cop aor p3 pl
"<.>"
	"." sent
```

Because you wouldn't know which token ID to give to `sent`. In the case of a sentence which is not fully disambiguated in CG then the link/button/tab for CoNLL-U would be greyed out.

**Comment by jonorthwash** [comment]
This is closely related to issue #1.  Please see [discusion starting here](https://github.com/jonorthwash/ud-annotatrix/issues/1#issuecomment-310183717).

**Comment by maryszmary** [comment]
> (from #1 ) per #40, once tokenised it should be automatically stored in conllu format

So, what you mean is that when a user converts a sentence to conllu, it is always stored in conllu since then (but can be viewed as CG)?

**Comment by jonorthwash** [comment]
> So, what you mean is that when a user converts a sentence to conllu,

When any sentence is dealt with by the system.  This isn't something the user should have to do—the system should automatically just do this for the user..

> it is always stored in conllu since then (but can be viewed as CG)?

Yes, exactly.

**Comment by maryszmary** [comment]
>> So, what you mean is that when a user converts a sentence to conllu,

> When any sentence is dealt with by the system. This isn't something the user should have to do—the system should automatically just do this for the user..

Ah, it actually was already converting input from CG to conllx before sending data to the brat visualiser. It is what cgParse in CG2conllx.js does.

**Comment by jonorthwash** [comment]
Yes.  Until recently it converted it to sdparse, which doesn't support POS tags.  Conllx might work as a backend—the main thing is that it be a superset of other formats (like CG, sdparse, etc.).  Otherwise we'll probably want to convert CG to conllu instead.

**Comment by ftyers** [comment]
conllx is not enough as it does not support spans, e.g.

```
"<бирчадыла>"
	"бирча" adj
		"э" cop aor p3 pl
```


Conllu

```
1-2  бирчадыла  
1     бирча
2    дыла

```

**Comment by jonorthwash** [comment]
Ah, good point.  There should be a comparison of the several formats somewhere.

**Comment by maryszmary** [comment]
I was stuck on this because I didn't see what architecture should be there to store and handle formats. In this issue, we were discussing that the system should *automatically* convert all the data to CoNLL-U. But there is of course a problem with ambiguous CG, which can't be converted.

Now I came up with the following:
1. After corpus uploading, the data are stored in the format it had.
2. There is a button `Convert the corpus to CoNLL-U`. When the user presses it, the whole corpus is converted to conllu, unless there are sentences with ambiguous analyses. In this case it shows the user a message saying that the data can't be converted.
3. There is also a button to `Convert the corpus to CG3`, which does the same, but for CG3.
4. There are buttons `View sentence as X`, where *x* is a format name, which doesn't convert the stored data, but just shows the current sentence in the text-area in the format wanted.
5. The graphical editing works for sentences stored in either CoNLL-U or unambiguous CG3.

I'm going to implement this behavior now.

**Comment by jonorthwash** [comment]
> 2. There is a button `Convert the corpus to CoNLL-U`. When the user presses it, the whole corpus is converted to conllu, unless there are sentences with ambiguous analyses. In this case it shows the user a message saying that the data can't be converted.

This is good.  At some point it should also take the user to the first ambiguous analysis, but this will be tricky to implement.  So we can file it as an enhancement and not worry about it for now.

> 3. There is also a button to `Convert the corpus to CG3`, which does the same, but for CG3.

So the corpus can be in either format natively, and you can convert it back and forth trivially.  The first part of this is excellent—I just worry some about data loss when converting back and forth is so easy.

> 4. There are buttons `View sentence as X`, where _x_ is a format name, which doesn't convert the stored data, but just shows the current sentence in the text-area in the format wanted.
> 5. The graphical editing works for sentences stored in either CoNLL-U or unambiguous CG3.

So this means you can only edit in the native format of the corpus, and if you want to edit in the other format, you'd have to convert the whole corpus.  While it would be harder to implement, it would be nice to have the `View sentence as X` tabs (I prefer the tab symbology, like the write/preview tabs in github issues, over buttons, but this is trivial and can be changed later) that allow you to edit (not just view) in either format as well, regardless of the corpus's native format.  How much extra work do you think this would be?

**Comment by ftyers** [comment]
I don't think there should be a button for Convert corpus to CG3. It isn't something we want to encourage. I agree with @jonorthwash that it would be nicer to have tabs.

**Comment by jonorthwash** [comment]
But editing in CG3 is easier than in CoNLL-U, at least if you're used to it.

Anyway, this issue now seems to be done!

**Comment by maryszmary** [comment]
Ok. Just a few notes:

> At some point it should also take the user to the first ambiguous analysis, but this will be tricky to implement. So we can file it as an enhancement and not worry about it for now.

I think, #10 is about it. But yeah, it's going to be tricky...

> I just worry some about data loss when converting back and forth is so easy.

There are 3 things that can be lost when converting from CoNLL-U to CG3:
1. XPOSTAG (especially if there is a UPOSTAG). I don't know how to solve this problem well.
2. Attribute names if FEATS. Now conversion doesn't remove them, but, as @ftyers said, If the features in conllu are feat=val pairs, then only the val should be shown in CG mode. But then the attribute names will be lost.
3. There is no place for MISC in CG3 format.

I don't know how these data can be represented in CG3. This lead me to the conclusion that when the corpus' native format is CoNLL-U, the interface should, when viewed in CG3, store a copy of the ĆoNLL-U sentence with all these data. The same actually should work when the sentence is viewed in plain text.
I'll create a new issue for this.

> So this means you can only edit in the native format of the corpus (or whatever it happens to be after converting), and if you want to edit in the other format, you'd have to convert the whole corpus.

So, I've already told you vk, but just to conclude: you don't have to convert the whole corpus to be able to edit the tree with gui. you can just edit it in CG, if the current sentence is not ambiguous.

> I don't think there should be a button for `Convert corpus to CG3`. It isn't something we want to encourage.

Ok, then I'll remove this button. For editing text in CG3, you can use the `View sentence as CG` button.

> I agree with @jonorthwash that it would be nicer to have tabs.

I'll create a new issue for this.

**Comment by ftyers** [comment]
Hmm, I didn't see the messages on VK...

**Comment by maryszmary** [comment]
ah, @ftyers, it was in the personal chat with Jonathan. I'll resend them to you.
