### ISSUE TITLE
Add a way of creating a new null node

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#403]
Maybe something like click on the node that you want to make the null node under and press a key like `n`? The index of the node should be 3.1 if there are no other nodes or n+1 if there are existing nodes. The null node can have a surface form, but cannot have any basic dependencies.

**Comment by ftyers** [comment]
Does this really close it? That looks like it toggles if a given node is empty, not a way of creating a whole new empty node? Can you post a gif of it working?

**Comment by kmurphy4** [comment]
Ah, I misunderstood. Yes this toggles whether a node is empty.

**Comment by ftyers** [comment]
I don't think that's a necessary function, we mostly need a way to add/remove empty nodes.

**Comment by JPJPJPOPOP** [comment]
@kmurphy4 @keggsmurph21 Now if I use the `n` shorcut twice in a row on the same token, it makes it a root. This basically allows me to make multiple roots which is not good.

**Comment by keggsmurph21** [comment]
> @kmurphy4 @keggsmurph21 Now if I use the `n` shorcut twice in a row on the same token, it makes it a root. This basically allows me to make multiple roots which is not good.

Oops, that was a mistake by me.  That behavior should be fixed in 04b5f5f.

**Comment by keggsmurph21** [comment]
> I don't think that's a necessary function, we mostly need a way to add/remove empty nodes.

@ftyers can you check if 02b3668 does what you expect?  I changed the toggling-whether-a-token-is-empty keybinding to <kbd>E</kbd> and bound this new one to <kbd>N</kbd> as you suggested.

**Comment by ftyers** [comment]
Looks good, now we just need a way of deleting them too :D
