### ISSUE TITLE
Graph doesn't show

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#404]
When doing plaintext -> conllu the graph doesn't show after converting to conllu.

```
$ firefox --version
Mozilla Firefox 74.0.1
```

**Comment by ftyers** [comment]
Weird firefox stuff going on.

**Comment by keggsmurph21** [comment]
I've noticed that sometimes the graph displays but it's not centered on the screen so it looks like nothing happened.
