### ISSUE TITLE
's' doesn't work to make a new MWT from two 

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#408]
Before you could use 's' and then left and right arrows to make two tokens into an MWT,

e.g.
```
1 foo
2 bar
```
* s left
```
1-2 foobar
1 foo
2 bar

Now it doesn't seem to work.

**Comment by JPJPJPOPOP** [comment]
@ftyers It seems like the shortcut is 'c' not 's'.

**Comment by keggsmurph21** [comment]
Yeah, <kbd>S</kbd> is bound to "split" and <kbd>C</kbd> is bound to "combine" (at least those were my mnemonics for the functionality).

**Comment by ftyers** [comment]
Previously it was `s` for supertoken and just middle click for split. I suppose the exact shortcut doesn't matter, but in general being backwards compatible is good.
