### ISSUE TITLE
Merge notatrix with annotatrix

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#415]
Is there any reason for having these two as separate at this point? As far as I know there are no other projects using `notatrix`, and having it as an external dependency has downsides:
* We have two issue trackers for what is essentially one project
* It adds a dependency so you always have to check if it's up to date.

If there were other projects using it, or wanting to use it, I could understand splitting the functionality, but at the moment it's just annotatrix and having it separate causes more problems than it solves.

**Comment by jonorthwash** [comment]
Note @keggsmurph21's comment at https://github.com/jonorthwash/ud-annotatrix/issues/397#issuecomment-636520902 :
> > I meant, when notatrix is updated, how does that code find its way into this repo?
> 
>     * make change to `notatrix` source code (e.g., [keggsmurph21/notatrix@4e27322](https://github.com/keggsmurph21/notatrix/commit/4e27322b0e27b64dbbda874f73b0a2b3ab89f173))
> 
>     * publish a new version on `npm` package registry (e.g., [keggsmurph21/notatrix@fb805ec](https://github.com/keggsmurph21/notatrix/commit/fb805ec68c74d7dcee6366d791f79573e4f71aaf)) via
>       ```shell
>       $ npm version patch
>       $ npm publish
>       ```
> 
>     * bump the required version in `ud-annotatrix`'s `package.json` (e.g., [b3a1ab4](https://github.com/jonorthwash/ud-annotatrix/commit/b3a1ab40291f3c50c00b5a78a3fadf783a610a34)) and then update the dependencies via
>       ```shell
>       $ npm install --save-dev
>       ```

This is a pretty convoluted dev cycle....

**Comment by keggsmurph21** [comment]
Yep!  I totally agree.

My original plan was to have notatrix as a general dependency annotation library that other projects could use, but that hasn't really happened :smile: .

I'm happy to move notatrix into this source tree, though.

**Comment by ftyers** [comment]
I've made a PR, #426 ... it seems to work on my system, but would appreciate a review/confirmation before merging it.
