### ISSUE TITLE
add help for users

### ISSUE THREAD

**Issue by maryszmary** [jonorthwash/ud-annotatrix#42]
There's already some functionality which needs to be describe, and there's going to be mush more.
I think, there should be a pop-over or a separate page with _help_.

**Comment by maryszmary** [comment]
Added the basic help in d812daa65f280fc7385d7bb0d6981c4c51553fb7. To call help, press the button `help` in the top right corner on the main page. The [help page](https://maryszmary.github.io/ud-annotatrix/standalone/help.html).

**Comment by ftyers** [comment]
Help page disappeared with the new style, perhaps it could have a "question mark" like icon ?

**Comment by ftyers** [comment]
I added it with the "support" icon in 60fb441, @jonorthwash is this ok or is there a better icon?

**Comment by jonorthwash** [comment]
Still working on this, with @sushain97's help.

**Comment by ftyers** [comment]
This was fixed at some point.
