### ISSUE TITLE
implement features not available in the graphing library

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#44]
This is a meta-issue for either adding things to the graphing library from brat (e.g., in a branch) or implementing them into a new library.
1. A `ROOT` node, or at least arrow.  There was a hack for this at one point (at least in CG format), where a root node was put on the left (node 0).  But ideally, it would be at a height just above all the arcs, center aligned right over the its dependent.
2. Vertical alignment of tree.  See #43.

There's more stuff that we've discussed, but I can't think of it all right now.

**Comment by ftyers** [comment]
Now we're using Cytoscape I think we can close this issue. The alignment is in #43 and the other issue can be reopened as a new issue if it's really important.
