### ISSUE TITLE
reordering sentences in conllu file

### ISSUE THREAD

**Issue by bkeej** [jonorthwash/ud-annotatrix#454]
The first sentence of conllu files is made last on upload. This is problem because on download the resulting conllu file is out of order. Here is a minimal example file to illustrate:

[test.txt](https://github.com/jonorthwash/ud-annotatrix/files/6502924/test.txt)

**Comment by keggsmurph21** [comment]
I think @ftyers fixed this in https://github.com/jonorthwash/ud-annotatrix/commit/7c050b996ee0324d435020384f99557cd738b008.  Please re-open this issue if you're still having this problem!
