### ISSUE TITLE
If UPOSTAG column is empty, display XPOSTAG if not empty

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#46]
See issue #36.

**Comment by maryszmary** [comment]
As far as I understand, things like that happen in brat's libraries. One more argument for rewriting the visualisation.

**Comment by ftyers** [comment]
Ok, if it's really involved, then concentrate on other stuff for now. :)

**Comment by maryszmary** [comment]
Implemented this while rewriting the visualization. E.g., the example from #36 without spans:
![image](https://user-images.githubusercontent.com/16348652/29138064-1b9f1592-7d4b-11e7-8641-749b6a47916d.png)

**Comment by maryszmary** [comment]
Can be closed probably? @ftyers ?

**Comment by ftyers** [comment]
Looks good.
