### ISSUE TITLE
Annotatrix merges tokens backwards

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#468]
![annotatrixfail](https://user-images.githubusercontent.com/449545/145499972-8ef956de-6aa9-4ebe-8d09-07cc974d005e.gif)

`o kse` should become `okse` not `kseo`.

**Comment by jonorthwash** [comment]
@ftyers, we're having trouble reproducing this, and @keggsmurph21 appears to have committed a fix in March.  Could you test that it's still an issue?  If so, could you post an example we can test with?

**Comment by ftyers** [comment]
This seems to be working now. 
![Peek 2022-06-10 16-43](https://user-images.githubusercontent.com/449545/173102279-0d0f2231-1407-4ef3-8cd1-bd1ebc5c9348.gif)
