### ISSUE TITLE
Help page has wrong keyboard shortcut

### ISSUE THREAD

**Issue by nschneid** [jonorthwash/ud-annotatrix#474]
https://github.com/jonorthwash/ud-annotatrix/blob/415327b7f0392b78bb5056619bede37cad89c2a5/server/views/help.ejs#L56

This should be `c`, not `s` (which is for splitting a token).

I would also reword the part about "select with an arrow" to "select with left/right arrow key or by clicking".

**Comment by ftyers** [comment]
Thanks for the report, fixed in https://github.com/jonorthwash/ud-annotatrix/commit/849b854c580a5954a8a5d61bada18c2285bd890c.
