### ISSUE TITLE
Spanning tokens not aligned properly

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#48]
The d'he should go before bugel.

![captura - 030817 - 16 47 29](https://user-images.githubusercontent.com/449545/28927897-03ece7c8-786c-11e7-9119-03bfad3d414e.png)

**Comment by ftyers** [comment]
This is probably related to #40 ?

**Comment by maryszmary** [comment]
Yes. At the moment, it is like this, because I've changed the sorting algorithm so that it displays a tree with spans at least in some way. I think, when I implement the span support, it will be fixed.

**Comment by maryszmary** [comment]
Doesn't do it since 87d2d4ff99394bef94d8688660620a5d6f82b73d.
