### ISSUE TITLE
interface for adjusting dependency relations

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#5]
Add an interface to ud-annotatrix for moving either end of a dependency link to another node.  Dependency relations are the arrows/lines between the various nodes.

**Comment by ftyers** [comment]
Duplicate of #35 #32 and #3

**Comment by jonorthwash** [comment]
This functionality doesn't seem to be mentioned in those other places.

**Comment by ftyers** [comment]
Could you describe what isn't in the other places ?

**Comment by jonorthwash** [comment]
With @maryszmary's most recent updates as of now, you can click head, then dependent, and it will make a new arc, replacing any other arc that would share the dependent.  Since it preserves the label, this essentially "moves" an arc from one parent to another.  There should be a similarly simple way to "move" an arc from a current head to a different head (preserving the label and the dependent).

**Comment by maryszmary** [comment]
I don't think I understand.
>  Since it preserves the label, this essentially "moves" an arc from one parent to another.

> There should be a similarly simple way to "move" an arc from a current head to a different head (preserving the label and the dependent).

From my point of view, _head_ and _parent_ are the same thing, so I don't see the difference between these functionalities.

**Comment by jonorthwash** [comment]
Sorry about that; I was confusing myself with some of this.  Let's try this again:

Currently we can easily change which _parent_ a dependent has.  We should also be able to easily move an arc to from one dependent to another, preserving the parent.

**Comment by maryszmary** [comment]
Ok. now it seems, I got it.
So, you want, say, in this case:
![image](https://user-images.githubusercontent.com/16348652/27510543-a59c1654-591b-11e7-8421-6b05288f3d71.png)

to be able to move the relation from the relation between `къатышды` and `соруу` to the relation between `къатышды` and `.` preserving the label `nsubj`?

**Comment by maryszmary** [comment]
(So, it something like remember the relation label at `къатышды` → `соруу` + delete `къатышды` → `соруу` + draw `къатышды` → `.` + add the relation label from `къатышды` → `соруу`?)

**Comment by jonorthwash** [comment]
Yeah, that's what I had in mind.  I can think of a couple different ways to implement something like this as far as the end user is concerned:
1. drag-and-drop,
2. select arc (mouse or arrows or number), keystroke for "move dependent", select new dependent (mouse or arrows or number).

**Comment by maryszmary** [comment]
> select arc (mouse or arrows or number), keystroke for "move dependent", select new dependent (mouse or arrows or number).

Done. To move an arc from one dependent to another, select an arc with click, then press `d` and select a node.
1.
![image](https://user-images.githubusercontent.com/16348652/27515722-f60571de-59b2-11e7-85a2-62660b268bd4.png)
2.
![image](https://user-images.githubusercontent.com/16348652/27515733-48065444-59b3-11e7-9daa-d7d4227d8b6e.png)

**Comment by maryszmary** [comment]
I guess, the issue can be closed?

**Comment by jonorthwash** [comment]
I'm not sure I like the fact that `d` needs to be pressed, but I think it'll do for now—it does seem to work okay.  After most of the main functionality is implemented, we'll probably want to go through and make a list of needed tweaks.

**Comment by maryszmary** [comment]
> I'm not sure I like the fact that d needs to be pressed

Actually, I agree. Maybe, it is worth get rid of this `d`? The user just needs to click on arc and then on a node. What do you think?

**Comment by jonorthwash** [comment]
> The user just needs to click on arc and then on a node. What do you think?

But then how will the user know which end of the arrow (dependent or head) is going to change?  I guess if it's just "the one that doesn't change by clicking on nodes" then that could work.
