### ISSUE TITLE
present a ROOT dependency in the graphs

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#50]
Per #44, as seen in red in attached screenshot.
![2017-08-05-15 16 22_002](https://user-images.githubusercontent.com/963849/28998138-3dc203e8-79f2-11e7-8745-5c963517994f.png)

**Comment by JPJPJPOPOP** [comment]
@jonorthwash How high should the root dependency be? I was thinking to just make as high or maybe like one level higher as the highest deprel.

**Comment by jonorthwash** [comment]
> @jonorthwash How high should the root dependency be? I was thinking to just make as high or maybe like one level higher as the highest deprel.

Good question, and those are probably both good variants to try.  I'd maybe start with the as-high version, and if that doesn't look good, try one higher?

**Comment by JPJPJPOPOP** [comment]
@jonorthwash Done.

**Comment by jonorthwash** [comment]
For record-keeping purposes, could you note the commit that this was fixed in?

**Comment by JPJPJPOPOP** [comment]
Here: https://github.com/jonorthwash/ud-annotatrix/commit/e9a2e20f391f6dc6d9f8de0114b02d38819770cd
