### ISSUE TITLE
Unable to access the local server

### ISSUE THREAD

**Issue by hezaoke** [jonorthwash/ud-annotatrix#506]
Hi!

I just started to use ud-annotatrix. I could access the local server and uploaded data files (with 1000 sentences) to the server and made changes to the tags and relations. However, somehow the server clashes after I return back to the history as the server froze (I realize that it might be because the data file is too big for the server). Now even after I restarted everything I could not access the local server any longer. Here is the error message I received if I would try to log into the serve again via the terminal:

> ud-annotatrix@1.0.0 dev-server
> nodemon src/server/app.ts --ignore corpora

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node src/server/app.ts`
ConfigError: Please provide ANNOTATRIX_GH_CLIENT_SECRET
Express server listening at http://localhost:5316
ENV: development
{
  port: 5316,
  host: 'localhost',
  protocol: 'http',
  corpora_path: 'corpora',
  secret: 'dev secret',
  environment: 'development',
  github: null,
  users_db_path: '.users',
  users: UsersDB { path: '.users.db' }
}
corpora/056a259a-8efe-4d9d-856f-c8ff5ff149c9.json
corpora/6a5d5a80-bb7f-42b5-9ca1-1dfd26777d29.json
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Users/mac/ud-annotatrix/src/server/list-treebanks.ts:51:55
    at Array.map (<anonymous>)
    at /Users/mac/ud-annotatrix/src/server/list-treebanks.ts:48:34
    at FSReqCallback.oncomplete (node:fs:203:5)
[nodemon] app crashed - waiting for file changes before starting...

Your help is much appreciated!
Alan

**Comment by keggsmurph21** [comment]
Thanks for the bug report! I pushed a change that should hopefully address the issue, but please re-open if that doesn't fix it for you!
