### ISSUE TITLE
issues with input handling

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#54]
There are some general issues with input handling at the moment:
1. Sometimes when merging tokens, the `m` keyboard shortcut results in an "m" input into the text box.  If focus is in the textbox and the graph is clicked on to merge, this still sometimes happens.
2. When splitting tokens, the [buggy] positioning of the input textbox sometimes makes both the graph and the entire page scroll.  Using the scroll wheel / trackpad scrolling to try to reposition the page can result in zoom in/out on the graph depending on the position of the cursor.  Perhaps page scrolling should be disabled entirely?

**Comment by maryszmary** [comment]
Hm, it will be probably easier to deal with when the bugs are split into 2 different issues.

**Comment by maryszmary** [comment]
Separated the issue into two new ones.
