### ISSUE TITLE
interface for editing POS tags

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#6]
Add an interface for editing POS tags, e.g., the tags like "VERB" in sentence 3 at http://universaldependencies.org/kk/dep/conj.html

**Comment by ftyers** [comment]
By default we can just include all the UD tags. But as an enhancement it would be nice to have an option to edit them.

**Comment by jonorthwash** [comment]
What do you mean we can include all the UD tags?  This issue is for begin able to specify/edit the POS tags.

**Comment by ftyers** [comment]
Ah, now I get what you mean, you mean like have a box under each of the syntactic words (nodes) where the POS is either there or can be specified/editted ? I'll decrease the milestone, this should easy to add.

**Comment by jonorthwash** [comment]
Yes, but currently there is already a box when a POS tag is specified.

**Comment by ftyers** [comment]
This seems to be fixed in @maryszmary's branch now.

**Comment by maryszmary** [comment]
Well, it is, but behavior is very buggy. I'll describe it in a new issue.

**Comment by jonorthwash** [comment]
Yeah, but this is probably a better approach at this point.  I.e., to close an issue once the basic functionality is there, and add a new issue (or issues) addressing any problems with it.
