### ISSUE TITLE
span text should not be behind the elements

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#61]
See here, where "hargle bargle" is behind "hargle" and "bargle":
![2017-08-12-12 59 10_001](https://user-images.githubusercontent.com/963849/29242600-0c9bb040-7f5e-11e7-9a7b-02973d3b889c.png)

It should probably be either above or below.

**Comment by maryszmary** [comment]
Now it is like this:
![image](https://user-images.githubusercontent.com/16348652/29339668-ec7a41a0-8223-11e7-85cd-5feeabff31ce.png)

**Comment by jonorthwash** [comment]
Great!
