### ISSUE TITLE
edge endpoints

### ISSUE THREAD

**Issue by maryszmary** [jonorthwash/ud-annotatrix#62]
At the moment, edges _from_ a node and _to_ a node intersect, so that it is impossible to understand, which edge comes to the node and which comes from it. E.g.: *text* and *a* in the example below.
![image](https://user-images.githubusercontent.com/16348652/29370185-4d1ae850-82ad-11e7-8251-1f60bb72f84e.png)

**Comment by jonorthwash** [comment]
The way [arborator](https://corpling.uis.georgetown.edu/arborator/q.cgi) does it is sensible:
![2017-08-26-15 17 03_001](https://user-images.githubusercontent.com/963849/29744373-b5f259aa-8a71-11e7-8fe8-151531995466.png)

**Comment by maryszmary** [comment]
@ftyers in #94:

> In brat you can have e.g. nmod> or <nmod, to show the direction of the arc in the label. We could use something like ◂ and ▸ symbols

**Comment by jonorthwash** [comment]
Yes, that's a good approach too, but there will need to be contingencies for situations like in the screenshot at the beginning of the issue, where there is no label yet.

**Comment by arademaker** [comment]
In that case you can use both arrows as default label.

**Comment by jonorthwash** [comment]
The new arrow solution is nice, but I still find myself annoyed by the overlapping labels.

I was looking into cytoscape and how things are implemented currently.  I think to fix this issue, the solution would be something like this:
1. When we create a "token" (using terminology from visualiser.js), we first need to create a +"r" and +"l" token, each staggered about 5% off the center of original token.
2. When we attach edges to the token (in makeDependencies()), we need to set `source` to `"nf" + headId + "l"` and `target` to `"nf" + nodeId + "l"`, respectively.

**Comment by jonorthwash** [comment]
Of relevance: https://github.com/cytoscape/cytoscape.js/issues/2013

**Comment by ftyers** [comment]
@jonorthwash in your (1) above are you suggesting making invisible "dummy" "tokens" that the arcs go into ? that are offset by a certain amount from the centre of the "real (visible) token" ?

**Comment by jonorthwash** [comment]
Yes, exactly.
