### ISSUE TITLE
issues with CG→conllu conversion

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#66]
1. The form column is empty.  If there's no form to put there, then it should be filled with `_`.
2. The POS tag of the second form is ending up in the morph tags column.

To demonstrate both of these:
```
"<Ерназардың>"
        "Ерназар" np ant m gen @nmod:poss #1->3
"<сегіз>"
        "сегіз" num @nummod #2->3
"<ұлы да>"
        "ұл" n px3sp nom @nsubj #3->7
                "да" postadv @advmod #4->3
"<соның>"
        "сол" prn dem gen @nmod:poss #5->6
"<ішінде>"
        "іш" n px3sp loc @obl #6->7
"<кетіпті>"
        "кет" v iv ifi evid p3 sg @root #7->0
"<.>"
        "." sent @punct #8->7
```
is currently converted as
```
1	Ерназардың	Ерназар	np	_	ant|m|gen	3	nmod:poss	_	_
2	сегіз	сегіз	num	_	_	3	nummod	_	_
3-4	ұлы да	_	_	_	_	_	_	_	_
3		ұл	n	_	px3sp|nom	7	nsubj	_	_
4		да	_	_	postadv	3	advmod	_	_
5	соның	сол	prn	_	dem|gen	6	nmod:poss	_	_
6	ішінде	іш	n	_	px3sp|loc	7	obl	_	_
7	кетіпті	кет	v	_	iv|ifi|evid|p3|sg	0	root	_	_
8	.	.	sent	_	_	7	punct	_	_
```
It should probably be more like this:
```
1	Ерназардың	Ерназар	np	_	ant|m|gen	3	nmod:poss	_	_
2	сегіз	сегіз	num	_	_	3	nummod	_	_
3-4	ұлы да	_	_	_	_	_	_	_	_
3	ұлы	ұл	n	_	px3sp|nom	7	nsubj	_	_
4	да	да	postadv	_	_	3	advmod	_	_
5	соның	сол	prn	_	dem|gen	6	nmod:poss	_	_
6	ішінде	іш	n	_	px3sp|loc	7	obl	_	_
7	кетіпті	кет	v	_	iv|ifi|evid|p3|sg	0	root	_	_
8	.	.	sent	_	_	7	punct	_	_
```

**Comment by maryszmary** [comment]
> The form column is empty. If there's no form to put there, then it should be filled with _.

If I get it right, there are never any forms for the subreadings in this format. Do you want the converter to split the multiword token on space if there is one, as you did in your example?

**Comment by maryszmary** [comment]
Wow, it seems that github automatically closes the issues, if there is a commit message saying "fixed #<issue number>". I didn't know. Anyway, now I've fixed both parts. Check it out.

**Comment by jonorthwash** [comment]
> Do you want the converter to split the multiword token on space if there is one,

Yes, that's probably the most sensible thing to do.

**Comment by jonorthwash** [comment]
The current behaviour seems to be to just leave it blank.  That'll do for now!
