### ISSUE TITLE
conllu-formatted text isn't rendered to a graph

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#67]
Currently when conllu-formatted text is pasted into the textbox, it doesn't render as a graph.  It also causes CG to not be converted until the page is refreshed.

**Comment by maryszmary** [comment]
Hm, strange: it works for me in firefox (mine is 55.0.2), but doesn't work in chromium. Should be something about browser compatibility...

**Comment by maryszmary** [comment]
For some reason, chromium (and probably your browser also) conflicts with either the undo manager I'm using or the order in which I'm loading the libraries. I'll switch it off for a while, until I find out, what's going on.

**Comment by maryszmary** [comment]
Oh wait! I think I realized what was the problem, now it works for me. Check it again, please.

**Comment by jonorthwash** [comment]
Yeah, I've been testing using chromium.  Seems to work now!

@ftyers was testing using firefox, though, and seemed to be having similar issues.  He should feel free to reopen the issue if it's not fixed for him.
