### ISSUE TITLE
Add RTL support to graph visualisation

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#70]
Test case: 
```
"<ئەم>"
	"ئەم" det dem sg @det #1->2
"<دەرمانە>"
	"دەرمان" n sg abs ezaclo @dobj #2->4
"<رۆژانە>"
	"رۆژانە" adj @amod #3->2
"<دەخۆم>"
	"خواردن" vblex tv pri p1 sg @root #4->0
"<.>"
	"." @punct #5->4
```

Current view: 
![captura - 260817 - 16 33 06rtl](https://user-images.githubusercontent.com/449545/29742274-4b1341b6-8a7c-11e7-9714-667c18b90a14.png)

**Comment by maryszmary** [comment]
Is this problem about token numbers visualisation? (I don't see what else is wrong here).

**Comment by ftyers** [comment]
Arabic script (also Hebrew and some others) is read from right to left, so it should be like:

ئەم دەرمانە رۆژانە دەخۆمە .

(If your browser does RTL properly...) Basically just reverse the display order of the tokens.

**Comment by maryszmary** [comment]
Ah, I see.

**Comment by maryszmary** [comment]
Done.

![image](https://user-images.githubusercontent.com/16348652/29752636-deadf454-8b6a-11e7-8fbf-5c412c1730c5.png)

![image](https://user-images.githubusercontent.com/16348652/29752638-ee994d1e-8b6a-11e7-8035-8256f7b524dd.png)

![image](https://user-images.githubusercontent.com/16348652/29752640-ffefae64-8b6a-11e7-93fb-a5f208edeb65.png)

**Comment by jonorthwash** [comment]
Instead of having a button, could it be done automatically based on unicode range?

And support embedded flips, like "The sign read 'דאס פיש' and he thought it was funny."  When I type this in a textbox, the order of דאס (first, but on the right) and פיש (second, but on the left) is correct—but they won't be displayed right using your algorithm.

Fwiw, there's a whole [unicode report](http://unicode.org/reports/tr9/) on this and related problems.

**Comment by ftyers** [comment]
@jonorthwash Yes I think the embedded stuff should be filed as a separate issue, but for the "detect if it is RTL", perhaps we can just use something like [this](https://stackoverflow.com/questions/12006095/javascript-how-to-check-if-character-is-rtl) -- the one at the bottom.

**Comment by jonorthwash** [comment]
Yeah, should work.  Also, +1 for mixing Avestan and Cyrillic :D

**Comment by jonorthwash** [comment]
Two remaining issues moved to #141 and #142.
