### ISSUE TITLE
ID numbers should be separate from the surface form

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#71]
Instead of appearing in the same box as the surface form they should appear in a box like the POS tag. Because otherwise they appear in the segmentation box and it looks weird. Also at the moment they are tiny and difficult to read. If we are planning to use IDs/numbers in the shortcut keys they should be more prominent.

**Comment by maryszmary** [comment]
Yeah, I know something like that should be done. It's harder to implement, and putting the numbers into the token box was a quick temporal solution.

**Comment by ftyers** [comment]
No problem, this is just a note to say it needs to be dealt with. Btw, can't you do it the same as you do the POS tags ?

**Comment by maryszmary** [comment]
I think, yes, but I'm afraid it might require some work to make it beautiful. (I can easily make it in an ugly way like boxes-with-numbers-under-the-boxes-with-POS, but I don't think this solution is any better than the way it works now).

**Comment by ftyers** [comment]
I think that would be fine for now. :)

**Comment by maryszmary** [comment]
So, do you want me to do this?

> I can easily make it in an ugly way like boxes-with-numbers-under-the-boxes-with-POS

**Comment by ftyers** [comment]
Yep! If it's quick and easy :)

**Comment by jonorthwash** [comment]
The quick and ugly fix should be a priority, because the subscript number is now becoming part of the text...

**Comment by maryszmary** [comment]
Yes, you are right, numbers being part of the text was the ugliest solution to make.
It seems, that I finally came up with a solution which is even better than a quick and ugly fix. Now it looks like this:
![image](https://user-images.githubusercontent.com/16348652/29797799-f269005e-8c61-11e7-9667-3c751a5b367a.png)

![image](https://user-images.githubusercontent.com/16348652/29797808-fa68a534-8c61-11e7-8f16-20b25e4b724a.png)
