### ISSUE TITLE
turn "view sentence as X" buttons into tabs 

### ISSUE THREAD

**Issue by maryszmary** [jonorthwash/ud-annotatrix#73]
From [#26 (comment)](https://github.com/jonorthwash/ud-annotatrix/issues/26#issuecomment-310857376) :

> I guess I kind of imagine tabs across the top of the textbox (like with github's comment box:). The default tab is something like "automatic" and as soon as it detects a format of input, it switches to the tab for that format (seemlessly—i.e., it just changes which is highlighted). So in this case, it would switch to the "plain text" tab, but then you could click the conllu or CG tab to view it or edit it in those formats. Further modifications to the contents of the plain text tab would only add/remove/edit tokens, and not change any of the dependencies or POS info (etc.) visible in the other formats.

**Comment by jonorthwash** [comment]
Fixed in commits https://github.com/jonorthwash/ud-annotatrix/commit/54dd0ce448b04b911ad2cba56c0aa614bfb8b659 and https://github.com/jonorthwash/ud-annotatrix/commit/c3d0ab0ef159779a2d78afb0ae6e3868e6df9007 .
