### ISSUE TITLE
"view as CG" shortcomings

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#78]
CG format isn't showing numbers (even when CoNLL-U text is numbered), and blank tags are converted to "undefined" (instead of remaining `_`).

Steps to reproduce:
1. Type a sentence, click convert to CoNNL-U.
2. Click view as CG.

**Comment by maryszmary** [comment]
> CG format isn't showing numbers (even when CoNLL-U text is numbered)

Hm, it's strange, but I can't reproduce the problem in my browsers (firefox and chromium):

![image](https://user-images.githubusercontent.com/16348652/30005952-70af0420-90f6-11e7-86ea-fff506abb2d2.png)

> blank tags are converted to "undefined" (instead of remaining _).

> Steps to reproduce:
>  1. Type a sentence, click convert to CoNNL-U.
>  2. Click view as CG.

Aha, I see. For me, it happens only to upostag, and, it seems, I know how to fix it.

**Comment by maryszmary** [comment]
Fixed the issue with *undefined*. Now it remains `_`.

**Comment by maryszmary** [comment]
About the issue with numbers:
1. Which browser do you use?
2. Could you make a screenshot of the problem?

**Comment by jonorthwash** [comment]
I've used both Firefox and mobile Chrome on Android.

Try raw text—just a sentence. I'll send a screenshot later.

**Comment by jonorthwash** [comment]
In chromium too:

![2017-09-03-22 38 22_001](https://user-images.githubusercontent.com/963849/30009741-b073271a-90f8-11e7-9b10-f3da3a6e7033.png)

**Comment by maryszmary** [comment]
Ah, wait, I thought, you were talking about the numbers in visual graph.
So, you are talking about token numbers in raw text in CG3 format when converting from not annotated text, right? I didn't think they should be there, if head is not present, that's why I didn't implement it. How should this example look in correct CG3?

**Comment by jonorthwash** [comment]
There shouldn't be targets, but each node should be labelled with its node number.  This will look like a #1-> etc. at the end of each line.  The targets will be filled in as they're connected.

**Comment by maryszmary** [comment]
Ok. Fixed now.

**Comment by jonorthwash** [comment]
Seems to work.
