### ISSUE TITLE
split multiple sentence when raw text is input

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#79]
When multiple sentences are input one-sentence-per-line, it seems to think they are in `sdparse` format.  Identification of `sdparse` should only happen when there are ()s somewhere (or something like that: e.g., this sentence wouldn't be identified right...).

**Comment by ftyers** [comment]
Now it should come up with 'unknown format'.

**Comment by jonorthwash** [comment]
Now = which commit?

**Comment by ftyers** [comment]
1bd65cad5dec6bf7f9ced6586daced523d3187aa
