### ISSUE TITLE
impossible to remove sentences

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#80]
Once there are multiple sentence in the corpus there seems to be no way to remove/clear them.  It also becomes impossible to convert sentences to CoNLL-U.

This has no result (note the "sentence 3 / 4"):
![2017-09-03-22 47 41_001](https://user-images.githubusercontent.com/963849/30009915-e9865c6a-90f9-11e7-8066-c057f65fdf01.png)

**Comment by maryszmary** [comment]
Added support for removing the current sentence.

**Comment by jonorthwash** [comment]
Seems to work?
