### ISSUE TITLE
negative sentence index

### ISSUE THREAD

**Issue by jonorthwash** [jonorthwash/ud-annotatrix#85]
It now seems to be possible to work your way back to negatively indexed undefined sentences?

![2017-09-05-00 17 41_001](https://user-images.githubusercontent.com/963849/30045053-b771cca6-91cf-11e7-8340-39cb4e55845c.png)

**Comment by ftyers** [comment]
This seems to have been fixed at some point. At least at "1" and the last thing the buttons are greyed out.

**Comment by jonorthwash** [comment]
Nope, still seems to be an issue.  If you import a large corpus, and keep pressing previous, it gives you negative numbers.

![2017-10-16-15 43 05_001](https://user-images.githubusercontent.com/963849/31631808-dc2dee74-b288-11e7-87f8-11ce7fb3ad38.png)

**Comment by ftyers** [comment]
Should be fixed in 1876c28, can you confirm ?

**Comment by jonorthwash** [comment]
Can't seem to trigger it anymore.  Thanks!
