### ISSUE TITLE
Table view for CoNLL-U format

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#91]
From @arademaker:  It would be great to have a way of viewing/editing the CoNLL-U format as a table instead of a text box, and be able to show/hide columns.

**Comment by arademaker** [comment]
Thank you @ftyers !  It will be helpful!

**Comment by jonorthwash** [comment]
Perhaps related to #74.

**Comment by ftyers** [comment]
We've added a preliminary table view, it cannot be editted at the moment, but we're working on it. Also planning to add support to hide values in columns.

![captura de 2017-10-31 19-44-13](https://user-images.githubusercontent.com/449545/32242776-f11eb6be-be73-11e7-8ab7-0e232d6f1805.png)

**Comment by jonorthwash** [comment]
@sushain97, see this solution.

**Comment by ftyers** [comment]
@jonorthwash when I said "we" i meant @sushain97 and me (mostly sushain) :D

**Comment by jonorthwash** [comment]
Ah, nice.  The two of us were discussing options for this sort of thing a week or two ago—glad to see it's moving forward ^_^

**Comment by ftyers** [comment]
Now it's editable, sorry @sushain97 I had to change the code quite a lot... 179ea98 

Next up:
* Show/hide columns
* Be able to resize the table area.

**Comment by ftyers** [comment]
Ok, show/hide columns works in 432e06e. @arademaker could you check that this works for you? Then I think we can close the issue.

**Comment by ftyers** [comment]
Question: Should we make only optional columns show/hideable? e.g. I don't see much point in hiding the ID/FORM columns, and to be honest, not sure about the HEAD/DEPREL columns either. 

Also, af7f975 fixes navigation issues (where the table wasn't updated when you switch sentences)

**Comment by ftyers** [comment]
Ok, table area now resizeable in 1cf325c. I think this completes the issue.

**Comment by arademaker** [comment]
nice to have this new table view. But I would expect to save space once a column is unmarked.  the screenshots below show that not much space was saved, the unchecked column should be really hidden from the table.

<img width="1214" alt="ud_annotatrix_1" src="https://user-images.githubusercontent.com/86403/32274884-cdf335c4-bee7-11e7-93d0-332907cb0834.png">

<img width="1214" alt="ud_annotatrix" src="https://user-images.githubusercontent.com/86403/32274881-ca3d4488-bee7-11e7-8b49-0f683b0ffbb4.png">

**Comment by ftyers** [comment]
Ok, @jonorthwash made this comment too. I'm unsure of how to show that there was a column there without coming up with a very complicated interface. How about if the column header is set to "" and just the ⚪ is left ? That should save quite a bit of space, but still show that there was a column there. Does that sound ok @arademaker ?

**Comment by ftyers** [comment]
Ok, committed in 25bef60 , closing this issue, any bugs please make new issues :)

**Comment by jonorthwash** [comment]
Can you add a quick thing to give you the column name if the ⚪ is hovered?  Also, I think ⏴ for "collapse" and ⏵for "expand" are probably better / more semantic than the circles.

**Comment by ftyers** [comment]
@jonorthwash done. My font doesn't have those unicode symbols.

**Comment by jonorthwash** [comment]
> done

which commit?

**Comment by ftyers** [comment]
468d5c9

**Comment by jonorthwash** [comment]
This commit seems to still have ⚫s?

**Comment by ftyers** [comment]
That commit was for "Can you add a quick thing to give you the column name if the ⚪ is hovered?". I didn't change the symbols because my font doesn't have them. If you want you can change them :)
