### ISSUE TITLE
No way to specify root node

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#92]
There doesn't seem to be a way to specify the root node.

**Comment by ftyers** [comment]
Current idea (from @maryszmary):

* Click on node
* Press 'r' 

And the node will get head = `0` and deprel = `root`. Perhaps we could also mark it some way, e.g. make the colour darker or something.

**Comment by jonorthwash** [comment]
> we could also mark it some way

Like having a hovering `ROOT` token above it that it's dependency of?  This would be my vote.

**Comment by ftyers** [comment]
You can now specify a root node by clicking on it and pressing 'r', fixed in 596379f. Future work would be either adding a `ROOT` token (but think about what that might do to the edge layout), or alternatively making the word bold or changing the format somehow (I prefer this), I tried to add bold format, but it didn't work. Also probably when you make something root, everything else that is labelled root should become undefined.

**Comment by jonorthwash** [comment]
> I tried to add bold format, but it didn't work.

Fixed in https://github.com/jonorthwash/ud-annotatrix/commit/91fe97221af0207adf70a259c82bee239d38fb7a and https://github.com/jonorthwash/ud-annotatrix/commit/81c1ed6d06704a1e82ec03ed7af0688173c53c29 .
