### ISSUE TITLE
detect invalid trees and advise the user

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#96]
Suggested by @fginter: If someone adds a cycle in the tree or does something else that isn't formally correct, then perhaps the background could turn another colour ?

**Comment by fginter** [comment]
That is how our annotator worked. Wrong stuff -> background very light red  Incomplete tree (missing deps) -> background white. Complete tree -> background very light green. It was very helpful in long sentences where it was easy to create cycles and whatnot.

**Comment by ftyers** [comment]
Here is one possible way to detect a cycle:

https://stackoverflow.com/questions/45716526/how-should-i-found-cycle-in-the-directed-graph-and-list-out-the-node-which-formi

**Comment by EthanProgramming** [comment]
Issue should be closed. Jonathan Pan and I added this feature.

**Comment by ftyers** [comment]
Looks like it works :)

![captura de 2018-01-13 14-45-13](https://user-images.githubusercontent.com/449545/34906576-70448d48-f870-11e7-9da6-f4e10b2a04ed.png)
